<?php
define("DB_DSN", "mysql:host=localhost;port=8889;dbname=intradb");
define("DB_USERNAME", "root");
define("DB_PASSWORD", "root");
define("EMAIL_SENDER", "info@jhm-zoetermeer.nl");
define("ADMINISTRATOR", "admin");
define("ADMIN_PASSW", "admin");

// define("DB_DSN", "mysql:host=localhost;dbname=prohuyg144_jhmiB");
// define("DB_USERNAME", "prohuyg144_jangg");
// define("DB_PASSWORD", "K1nsrijk&123");
// define("EMAIL_SENDER", "jang@jhmz.nl");
// define("ADMINISTRATOR", "admin");
// define("ADMIN_PASSW", "admin");

// smtp gegevens voor forum email
define("MAIL_SMTP_SERVER", "mail.axc.nl");
define("MAIL_USERID", "intra@jhmz.nl");
define("MAIL_PASSWORD", "Opgep1st!");
define("MAIL_SMTPSECURE", "ssl");
define("MAIL_SENDEREMAIL", "intra@jhmz.nl");
// DEBUg: 0 = none, 2 = normal, 3 = a lot 
define("MAIL_DEBUG_IND", "0");


// Overige CONSTANTS
// JobHulpMaatje Zoetermeer
define("LOC_NOREPLY_EMAIL", "no-reply@jhm-zoetermeer.nl");
define("LOC_COORD_EMAIL", "coordinator@jhm-zoetermeer.nl");
define("LOC_NAME", "JobHulpMaatje Zoetermeer");
define("LOC_LOGO", "Logo_JobHulpMaatje_Zoetermeer.svg");
define("LOC_DOMAIN", "intra.jhmz.nl");

// JobHulp Culemborg
// define("LOC_NOREPLY_EMAIL", "no-reply@jhculemborg.nl");
// define("LOC_COORD_EMAIL", "coordinator@jhculemborg.nl");
// define("LOC_NAME", "JobHulp Culemborg");
// define("LOC_LOGO", "stichtingjobhulpculemborg1.jpg");
// define("LOC_DOMAIN", "intra.jhc.nl");

?>