<?php
define("DB_DSN", "mysql:host=localhost;port=8889;dbname=jhmi");
define("DB_USERNAME", "root");
define("DB_PASSWORD", "root");
define("EMAIL_SENDER", "info@jhm-zoetermeer.nl");
define("ADMINISTRATOR", "admin");
define("ADMIN_PASSW", "admin");

// define("DB_DSN", "mysql:host=localhost;dbname=prohuyg144_jhmi");
// define("DB_USERNAME", "prohuyg144_jangg");
// define("DB_PASSWORD", "Opgep1st");
// define("EMAIL_SENDER", "jang@jhm-zoetermeer.nl");
// define("ADMINISTRATOR", "admin");
// define("ADMIN_PASSW", "admin");



?>