<?php

function getMsgs ($number, $naam)
{
$newsmsg = array();

$newsmsg[11] = '<h3 class="bluefont" id="jaarverslag">Hoe was 2024 voor JobHulpMaatje Zoetermeer?</h3>
				<h5 class="bluefont">14-3-2025</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/jaarverslag2024.jpg" class="figure-img img-fluid" alt="jaarverslag 2024">
				<figcaption class="figure-caption">Jaarverslag voorpagina</figcaption>
				</figure>
				<p>Het afgelopen jaar was voor JobHulpMaatje weer een succesvol jaar. Samen met alle maatjes zijn ook in 2024 weer vele mensen geholpen in hun zoektocht naar passend werk.</p>
				<p>De meer dan 35 workshops en de vele Walk&Talk\'s zijn goed bezocht. Tot slot werd ook de afsluitende avond met de partners van JobHulpMaatje in stijl gehouden in een voor iedereen plezierige ambiance.</p>
				<p>Dit alles is terug te lezen in het jaarverslag over 2024. Als je ook nog wilt weten hoe de euro\'s rolden, lees dan het financieel jaarverslag.</p>
				<p><a class="btn btn-primary" href="https://jobhulpmaatjezoetermeer.nl/nieuws.php" role="button target="_new">Naar het jaarverslag 2024 &raquo;</a></p>
				';



$newsmsg[10] = '<h3 class="bluefont">Verslag maatjesavond</h3>
				<h5 class="bluefont">13-3-2025</h5>
				<p>De eerste maatjesavond zit er weer op. En er was veel informatie. Peter heeft een kort verslag geschreven dat je kunt lezen via onderstaande knop.</p>
				
				<p><a class="btn btn-primary" href="pages/bericht20250313_1.php" role="button">Verslag lezen &raquo;</a></p>
				<figure class="figure float-right" style="width: 100%; margin-left: 0px;">
				<img src="img/maatjesavond2503121.jpg" class="figure-img img-fluid" alt="Maatjesavond">
				</figure>

				';
				

$newsmsg[9] = '<h3 class="bluefont">Eerste maatjesavond van 2025</h3>
				<h5 class="bluefont">20-2-2025</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/stadhuisforum.jpg" class="figure-img img-fluid" alt="stadhuisforum">
				</figure>
				<p>Hierbij nodigen wij je uit voor de eerste maatjesavond van dit jaar in het Forum.</p>
				
				<p> We zijn nog niet helemaal zeker van de agenda. Deze volgt zodra we \'m definitief hebben vastgesteld. In ieder geval zal het gebruik van de testen bij het LDC een grote rol spelen.</p>
				<p>Veel maatjes hebben al via Whatsapp laten weten of ze komen of niet. Toch willen we je vragen dat ook nog te laten weten in de presentielijst die je ziet als je onderstaande knop gebruikt. Een antwoord daar kun je elk moment weer wijzigen als je dat nodig vindt.</p>
				<p>Uiteraard hopen we op je aanwezigheid. Niet alleen omdat het nuttig is maar misschien nog wel meer omdat we je graag zien en spreken!</p>
				<p>Tot dan.<br/>Joke en Marius</p>
				
				<p><a class="btn btn-primary" href="#" role="button">Maatjesavond aan/afmelden &raquo;</a></p>
				
				';
				
				
$newsmsg[8] = '<h3 class="bluefont">Nieuwe brochure</h3>
				<h5 class="bluefont">17-1-2025</h5>
				<p>Ook dit jaar verzorgt JobHulpMaatje weer een flink aantal workshops voor mensen die graag wat hulp ontvangen bij het zoeken naar werk.</p>
				<p>De meeste workshops worden als vanouds vakkundig verzorgd door Flip Bakker. Enkele workshops, ieder met een specifiek thema, worden door diverse gastsprekers verzorgd.</p>
				<p>We hopen uiteraard op een flinke belangstelling en zullen regelmatig via de Social Media bekend maken wanneer de workshops worden gehouden.</p>
				<p>Wil je de bijbehorende brochure zien? Klik dan op de button.</p>
				<p><a class="btn btn-primary" href="pages/bericht20250117_1.php" role="button">Bekijk de flyer &raquo;</a></p>
				<figure class="figure float-left" style="width: 100%; margin-right: 0px;">
				<img src="img/2025voorjaarsprogramma1.jpg" class="figure-img img-fluid" alt="flyer">
				</figure>

';
$newsmsg[7] = '<h3 class="bluefont">Nieuwe berichten</h3>
				<h5 class="bluefont">5-12-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/firefoxnbs.png" class="figure-img img-fluid" alt="nieuwsberichten">
				</figure>
				<p>Op de publieke website staan nu twee nieuwe berichten. Misschien niet voor iedereen nieuws maar toch belangrik genoeg om de nieuwsfeiten op de website onder de aandacht te brengen.</p>
				<p>Klik op bijgaand knop om ze te lezen.</p>
				<p><a class="btn btn-primary" href="https://jobhulpmaatjezoetermeer.nl/nieuws.php" role="button">Lees het nieuws &raquo;</a></p>
';


$newsmsg[6] = '<h3 class="bluefont">Kerst Maatjesavond</h3>
				<h5 class="bluefont">1-12-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/kerstborrel.jpg" class="figure-img img-fluid" alt="kerstborrel">
				</figure>
				<p>Het jaar loopt weer ten einde, tijd om weer de rekening op te maken van onze activiteiten in het afgelopen jaar. Op maandagavond 16 december as. vanaf 19:30h ben je welkom in de Kapelaan.</p>
				<p>Deze avond besteden we aan een terug- en aan een vooruitblik van JobHulpMaatje in onze gemeente. Wat ging goed (veel!) en wat kan nog beter (altijd wel iets toch?).</p>
				<p>Bovendien hopen we nog veel meer mensen te mogen begroeten deze avond. Wie? Dat volgt later. Het belooft een feestelijke avond te worden.</p>
				<p>Wees erbij om het mee te maken en schrijf je in! Noteer 16 december in je agenda.</p>
				
				<!-- <p><a class="btn btn-primary" href="pages/presence_list.php" role="button">Ik kom naar de Maatjesavond &raquo;</a></p> -->
				
';


$newsmsg[5] = '<h3 class="bluefont">Persbericht JobHulpMaatje in het Streekblad</h3>
				<h5 class="bluefont">28-11-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/persbericht241128.jpg" class="figure-img img-fluid" alt="persbericht">
				</figure>
				
				';


$newsmsg[4] = '<h3 class="bluefont">Presentatie Peter Veld van 4-11-2024</h3>
				<h5 class="bluefont">6-11-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/presentatie-PV.jpg" class="figure-img img-fluid" alt="presentatie">
 				</figure>
				<p>Op de laatste maatjesavond van 4 -11-2024 gaf Peter Veld een presentatie over de werkgelegenheidsproblematiek in Zoetermeer en omgeving. Op veler verzoek kun je hier de integrale 
				presentatie vinden in PDF-formaat. Deze is te downloaden. Als je op onderstaande link drukt, kun je de presentatie als download zo binnenhalen.</p>
				
				<p><a href="docs/presentatie04112024.pdf" download="presentatie04112024.pdf">Presentatie 4-11-2024&nbsp&nbsp&nbsp;<i class="fas fa-download"></i></a></p>
				';


$newsmsg[3] = '<h3 class="bluefont">Derde maatjesavond van 2024</h3>
				<h5 class="bluefont">13-9-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/stadhuisforum.jpg" class="figure-img img-fluid" alt="stadhuisforum">
 				</figure>
				<p>Hierbij nodigen wij je uit voor de derde maatjesavond van dit jaar in het Forum.
				
				We sluiten om 21:30 uur af. Wie wil, kan blijven voor onderling contact. We zorgen voor wat drinken en lekkers daarbij. Om 22:00 uur moeten we het pand écht verlaten.</p>
				<table>
					<tr><td>Datum</td><td>Woensdag 18 september 2024</td></tr>
					<tr><td>Plaats</td><td>Stadhuis Forum</td></tr>
					<tr><td></td><td>beneden in de Commissiezaal/trouwzaal</td></tr>	
					<tr><td>Tijdstip</td><td>Ontvangst vanaf 19:15h</td></tr>
					<tr><td>Aanvang</td><td>19:30h</td></tr>
					<tr><td>Einde</td><td>21:30h</td></tr>
					<tr><td></td><td>Nazit tot uiterlijk 22:00h</td></tr>
				</table><br/>
				<p>Programma</p>
				<table>
					<tr><td>19:30h&nbsp;&nbsp;</td><td>Opening en welkom door Joke</td></tr>
					<tr><td>19:40h&nbsp;&nbsp;</td><td>Mededelingen van bestuur en coördinatoren</td></tr>
					<tr><td>19:50h&nbsp;&nbsp;</td><td>Peter licht nieuwe ontwikkelingen en activiteiten toe</td></tr>	
					<tr><td>20:10h&nbsp;&nbsp;</td><td>Pauze</td></tr>
					<tr><td>20:30h&nbsp;&nbsp;</td><td>Werkwijze en gezamenlijke afspraken door Flip en Marius.</td></tr>
					<tr><td></td><td>De werkwijze van JobHulpMaatje in Zoetermeer is in de loop van de tijd wat losser geworden en misschien wel iets veranderd. Het gaat dan vooral om werkvolgorde en procedures. We willen hierover spreken, van gedachten wisselen en de neuzen weer meer in dezelfde richting krijgen. Maar ook andere zaken die het Maatje-zijn betreffen kunnen aan de orde komen.</td></tr>
					<tr><td>21:20h</td><td>Rondvraag</td></tr>
					<tr><td>21:30h&nbsp;&nbsp;</td><td>Sluiting</td></tr>
				</table><br/>
				  				
				<p>Je aanwezigheid is, zoals altijd, belangrijk! Samen maken we JobHulpMaatje en kunnen we meer betekenen voor onze medemens. We zien naar je uit.
				Laat even weten of je al dan niet van plan bent om te komen via Intranet, of anders aan Joke. Dat helpt ons in de voorbereidingen. Er is plaats voor 76 personen, dus leuk als je er bent 😊</p>
				<p>Als je nog niet hebt aangegeven of je komt of niet, doe dat ajb dan nu. Bij het invullen van de aanmeldingslijst lees je hoe je dat doet.</p>
				<p><a class="btn btn-primary disabled" href="#" role="button">Maatjesavond aan/afmelden &raquo;</a></p>
				
				';

$newsmsg[2] = '<h3 class="bluefont">Najaarsprogramma 2024</h3>
				<h5 class="bluefont">16-8-2024</h5>
				<p>De vakanties zijn bijna voorbij. Mensen gaan weer aan het werk. Of willen dat juist heel graag en zoeken een baan. Wij helpen daarbij, ook dit najaar.</p>
				<p>Het bestuur en de coördinatoren hebben ook voor het najaar van 2024 een programma opgesteld met workshops voor iedere werkzoekende. En voor de gelegenheid is weer een prachtige brochure 
				ontworpen.</p>
				<p>Het programma staat in de agenda van het intranet. Je kunt de flyer downloaden via de publieke website via onderstaande knop. Er is <a href="https://jobhulpmaatjezoetermeer.nl/nieuws">een nieuwsbericht op de website</a> waarnaar je kunt verwijzen als iemand meer informatie wil hebben.</p>
				<figure class="figure float-right" style="width: 100%; margin-left: 15px;">
				<img src="img/2024najaarsprogramma.jpg" class="figure-img img-fluid" alt="2024najaarsprogramma">
 				</figure>
				<p><a class="btn btn-primary" href="https://jobhulpmaatjezoetermeer.nl/stichting.php#downloads" role="button">Download hier de flyer &raquo;</a></p>
				';


$newsmsg[1] = '<h3 class="bluefont">Multiproblematiek</h3>
				<h5 class="bluefont">25-4-2024</h5>
				<p>Ook op de laatste maatjesavond kwam het onderwerp weer ter sprake: multiproblematiek. Duidelijk is dat dit begrip vaak een grote rol speelt bij de mensen die JobHulpMaatje op dit moment ondersteunt bij het zoeken naar geschikt werk. Want vaker wel dan niet spelen er meerdere zaken bij het vinden van passend werk. Zoals gezondheid, zowel lichamelijk als geestelijk, armoede, etniciteit, leeftijd, enz.</p>
				<p>Afgelopen zaterdag stond in het NRC een artikel waarin goed werd uitgelegd wat dit betekent voor mensen. En ook hoe lastig het kan zijn om deze mensen goed te helpen.</p>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/saskiabrandewijn.png" class="figure-img img-fluid" alt="saskiabrandewijn">
				<figcaption class="figure-caption"><b>Saskia Brandewijn</b> kan door psychische problemen niet werken, maar krijgt geen arbeidsongeschiktheidsuitkering. „Wat maakt het uit of ik eerst gewerkt heb? Ik ben gewoon ziek.”</figcaption>
				 </figure>
				<p>Het artikel gaat voornamelijk over mensen die in de bijstand zitten en ziek zijn. Deze mensen ervaren op meerdere terreinen tegenslag en onbegrip. Mensen met wie ook wij soms te maken krijgen. Vandaar dat dit artikel lezenswaardig is voor ieder maatje.</p>
				<p><a class="btn btn-primary" href="docs/nrc-krant-20240420-4995671.pdf" role="button">Lees het artikel &raquo;</a></p>
				';

$newsmsg[0] = '<h3 class="bluefont">Verslag maatjesavond van 10 april</h3>
				<h5 class="bluefont">24-4-2024</h5>
				<p>De laatste maatjesavond vond twee weken geleden plaats. Niet iedereen was aanwezig. Hier kun je een kort verslag lezen dat Sjanet heeft gemaakt.</p>
				<p><a class="btn btn-primary" href="pages/bericht20240424_1.php" role="button">Lees het verslag &raquo;</a></p>
				';


	return $newsmsg;

}
