<?php

function getMsgs ($number, $naam)
{
$newsmsg = array();

$newsmsg[34] = '<h3 class="bluefont" id="jgtrainingg">JobGroup-trainer worden</h3>
					<h5 class="bluefont">10-1-2022</h5>
					<p>Het geven van een JobGroup-training is één van de leukste activiteiten voor vrijwilligers die we bij JobHulpMaatje hebben. Je geeft je kennis en ervaring door aan zeer gemotiveerde mensen die graag aan de slag willen op de Nederlandse arbeidsmarkt.</p>
					<img src="img/jobhulpmaatje.jpg" class="my-2 float-right" style="width: 100%; margin-left: 15px;" alt="JobGroup">
					<p>JobHulpMaatje Zoetermeer doet dat alle enige jaren, met succes. En we verwachten dat het in de toekomst eerder drukker wordt dan rustiger. Daarom de vraag aan ieder maatje: wie wil opgeleid worden tot JobGroup-trainer? Als trainer word je minimaal 1 keer per jaar ingezet als trainer voor een JobGroup. Een JobGroup bestaat uit 7 of 10 dagdelen (ochtenden of middagen) en wordt meestal gegeven in het Forum/Bibliotheek van Zoetermeer. Een training geef je ook altijd met z\'n tweeën. Je staat er dus nooit alleen voor. ;-)</p>
					<p>Vrijdag 28 januari start een nieuwe training voor toekomstige JG-trainers. Als je interesse hebt, kun je je <a href="https://jobhulpmaatje.nl/aanmelden-trainingen/?deelnametype=Maatjestraining&locatie=Online" target="_new">hier</a> inschrijven. Of geef je naam door aan <a href="mailto:joke@jhm-zoetermeer.nl">Joke</a> of <a href="mailto:jang@jhm-zoetermeer.nl">Jan</a>. Dan zorgen zij voor verdere aanmelding. Doe dat dan wel graag vóór 15 januari a.s. Na afloop ben je een gecertificeerd JobHulpMaatje JobGroup-trainer.</p>
					<p>Een volgende training vindt plaats in mei van dit jaar. Uiteraard is dat ook een mogelijkheid om opgeleid te worden. Laat het weten bij je coordinator ajb.</p>
					';



$newsmsg[33] = '<h3 class="bluefont" id="dubbelslag">Het JobHulpMaatje schoolplein</h3>
					<h5 class="bluefont">28-12-2021</h5>
					<p>JobHulpMaatje Zoetermeer is een vrijwilligersorganisatie. En helaas zien wij, de vrijwilligers, elkaar slechts zelden. Er is weinig gelegenheid, zeker onder de huidige omstandigheden, met elkaar koffie te drinken, met elkaar bij te praten, te lachen en te mijmeren. We hebben geen eigen locatie en ook geen vaste momenten waarin we bezig zijn voor JobHulpMaatje.
					Voor het verspreiden van de informatie over en van JobHulpMaatje hebben we gelukkig het intranet. Dat probeert iedereen op de hoogte te houden met berichten en de agenda. Is het belangrijk? Dan staat het erop.</p>
					
					<img src="img/whatsapp/nopictures.png" class="my-2 float-left" style="width: 40%; margin-right: 15px;" alt="nopictures">
					<h5>De WhatsApp groepsapp</h5>
					<p>Maar dat gaat slechts één kant op. Gelukkig is er ook nog de groepsapp van WhatsApp. Hierin is iedereen opgenomen die actief is bij JobHulpMaatje Zoetermeer. De Whatsapp groepsapp is als een schoolplein. Wat je daar zegt kan iedereen lezen en zien. En iedereen kan reageren. En het is vluchtig. Wat je er vandaag op zet, is morgen misschien wel weer achter de horizon verdwenen.</p>
					
					<p>De Whatsapp groep is dus belangrijk voor ons. Maak er gebruik van als je iets kwijt wilt aan je mede-vrijwilligers. Liefst iets wat met JobHulpMaatje te maken heeft maar ook felicitaties bij verjaardagen of andere dingen die je graag aan je collega’s kwijt wil mogen hier worden geplaatst. Zo hebben we contact met elkaar, ook al is maar het digitaal. En dat is belangrijk.</p>
					<img src="img/whatsapp/getaroom.png" class="my-2 float-right" style="width: 40%; margin-left: 15px;" alt="getaroom">
					<p>Er zijn wel een paar regels die eigenlijk vanzelfsprekend zijn:</p>
					<ol>
					<li>Blijf fatsoenlijk</li>
					<li>Blijf beleefd</li>
					<li>Blijf terzake</li>
					</ol>
					<p>Als het nodig is kan er ingegrepen worden. Maar hé! We zijn toch allemaal nette mensen bij JobHulpMaatje Zoetermeer? Dus het zal wel meevallen <nobr>;-)</nobr></p>
					<img src="img/whatsapp/okbye.png" class="my-2 float-left" style="width: 40%; margin-right: 15px;" alt="okbye.png">
					<p>Als je niet houdt van meekletsen op een schoolplein dan kun je besluiten alleen mee te luisteren. Als je daar ook niet van houdt dan kun je het schoolplein natuurlijk ook verlaten. Toegang is niet verplicht. Doe alleen mee als het het leuk of nuttig vindt. Of beide natuurlijk! Want juist onder deze uitzonderlijke omstandigheden moeten we elkaar zoveel mogelijk vasthouden, ook in 2022 en verder.</p>
					';


$newsmsg[32] = '<h3 class="bluefont" id="dubbelslag">Dubbelslag in het Streekblad</h3>
					<h5 class="bluefont">17-12-2021</h5>
					<p>Deze week werd JobHulpMaatje Zoetermeer tweemaal in het Streekblad vermeld. Het komende afscheid van Johan en de afloop van de JobGroup waren de moeite waard om onder de aandacht te brengen.</p>
					<figure class="figure">
  						<img src="img/IMG_1607.jpeg" class="figure-img img-fluid" alt="Streekblad 1">
					</figure>
					<figure class="figure">
					  <img src="img/IMG_1608.jpeg" class="figure-img img-fluid" alt="Streekblad 2">
					</figure>
					';


$newsmsg[31] = '<h3 class="bluefont" id="nieuwjaarsbijeenkomst">Nieuwjaarsbijeenkomst</h3>
					<h5 class="bluefont">13-12-2021</h5>
					<p>Ook het jaar 2021 is weer een bijzonder jaar geworden, het tweede jaar op rij. Het virus heeft dit jaar grote gevolgen gehad voor de samenleving, voor de arbeidsmarkt en voor JobHulpMaatje.</p>
					</p>En het Corona-virus is nog niet klaar met ons allemaal. Kijk maar om je heen en je weet het: ook 2022 wordt niet zoals het ooit vroeger was.</p>
					<p>Maar dit alles is natuurlijk geen reden om bij de pakken neer te zitten. JobHulpMaatje Zoetermeer heeft, zo goed en zo kwaad als het ging, ook in 2021 goed werk verricht. Exacte cijfers heb ik nog niet maar 
					we mogen weer best trots zijn op onszelf en op wat we bereikt hebben. Helaas zit een klein feestje op dit moment er even niet in. We stellen dat uit tot een later moment als de situatie flink verbeterd is.</p>
					<p>Wat we echter wel graag willen doen is op een gepaste wijze het nieuwe jaar aftrappen. Bijvoorbeeld met een kleine nieuwjaarsreceptie waarop we kunnen toasten op 2022.</p>
					<figure class="figure">
					  <img src="img/de-kapelaan.jpg" class="figure-img img-fluid" alt="De Kapelaan">
					</figure>
					<p>We houden daarom de bijeenkomst op <strong>donderdag 20 januari</strong> in de Kapelaan in de Dorpsstraat. Geplande tijd is van 17:00 tot 19:00 uur. We beseffen dat veel afhankelijk is van de omstandigheden. 
						Mogelijk wordt de receptie verplaatst naar het pleintje voor de Kapelaan, onder parasols en met wat vuurkorven als warmtebron. We doen er alles aan om het door te laten gaan.</p>
					<img src="img/vuurkorf.jpg" class="my-2 float-right float-right" style="width: 20%; margin-left: 15px;" alt="vuurkorf">
					<p>Het is prettig als je met de intekenlijst laat weten of je komt of niet. Klik op onderstaande knop hiervoor. We zien je graag in januari en hopen dat we met z\'n allen een goed jaar tegemoet gaan.</p>
					<a class="btn btn-primary" href="pages/presence_list220113.php" role="button">receptie aan/afmelden &raquo;</a></p>
					';

$newsmsg[30] = '<h3 class="bluefont" id="jobgroup2021-3">Laatste JobGroup van 2021 afgesloten</h3>
					<h5 class="bluefont">12-12-2021</h5>
					<figure class="figure">
					  <img src="img/IMG_1570.jpeg" class="figure-img img-fluid" alt="JobGroup 2021-3">
					  <figcaption class="figure-caption">Staand van links naar rechts: Paul, Mona, Vivian. Zittend: Jan, Paula.</figcaption>
					</figure>
					<p>Afgelopen vrijdag 10 december sloten we de laatste JobGorup van dit jaar af. Door de coronamaatregelen moesten we uitwijken naar Café Max in de bibliotheek. 
					Een café dat overigens nog niet in gebruik is en daarom door ons gebruikt mocht worden. Niet ideaal maar dat ons aanpassingsvernmogen is groot is bleek uit de prima presentaties die de afsluitende deelnemers lieten horen. 
					Na het commentaar, de tips en de tricks van de toehoorders  en het uitreiken van de certificaten,
					was het tijd voor napraten en een lekkere tractatie.</p>
					<p>Afgesproken is dat de jobgroupleiders en de deelnemers over ruim een maand weer samenkomen om te kijken hoe het ieder vergaat. En intussen willen ze allemaal graag een maatje voor een persoonlijke begeleiding. Ook
					dat gaan we regelen natuurlijk.</p>
					
					';



$newsmsg[29] = '<h3 class="bluefont">Weer in het Streekblad</h3>
					<h5 class="bluefont">11-11-2021</h5>
					<p>Met een mooi stuk over de afsluiting van de JobGroup ZZP die op 5 november jl. plaats vond, is Corrie Buren er weer in geslaagd JobHulpMaatje Zoetermeer onder de aandacht te brengen in het Streekblad.</p>
					<img src="img/IMG_1444.jpeg" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Streekblad">
					';



$newsmsg[28] = '<h3 class="bluefont">Nieuwe posters en flyers</h3>
					<h5 class="bluefont">8-11-2021</h5>
					<img src="img/IMG_1442.jpeg" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Posters">
					<p>De mensen waarop JobHulpMaatje zich richt zijn niet altijd makkelijk te bereiken. En juist nu, in deze Corona-tijd, zijn velen voorzichtig met het zoeken van hulp. Ook onze hulp.</p>
					<p>Daarom willen we de toegang tot onze diensten zo laagdrempelig mogelijk aanbieden. Heel belangrijk daarbij is dat JobHulpMaatje als naam bekend wordt bij allerlei andere organisaties die hulp bieden op vele terreinen.
					Organisaties als Piëzo, Inzet, het Leerwerkloket, SchuldHulpMaatje etc. zijn, net als wij, in de weer om mensen die het nodig hebben en dat ook willen, aan een betere en sterkere maatschappelijke positie te helpen.</p>
					<p>Met nieuwe posters die we op zoveel mogelijk plaatsen willen op hangen en flyers die we kunnen uitdelen, hopen we bekender te worden. Zodat mensen ons makkelijk en snel kunnen vinden en wij ze verder helpen bij het vinden van 
					passend werk.</p>
					
					<p>Weet jij ook nog plekken waar deze posters zouden kunnen hangen? Laat het even weten met een email naar <a href="mailto: corrieburen@kpnmail.nl">Corrie Buren</a> of <a href="mailto: jang@jhm-zoetermeer.nl">Jan Geerdes</a>.
					Zij zorgen ervoor dat je snel het materiaal binnen krijgt en het kan gebruiken. Zoetermeer verdient het.
					Alvast bedankt!</p>
					';



$newsmsg[27] = '<h3 class="bluefont">Uitnodiging studiemiddag geldzaken</h3>
					<h5 class="bluefont">4-11-2021</h5>
					<h2>15-11-2021 AFGELAST! vanwege Corona</h2>
					<p>De gemeente Zoetermeer neemt op veel gebieden initiatief om armoede binnen de gemeentegrenzen te bestrijden. Een belangrijk aandachtspunt is er voor geldzaken, alles dat te maken heeft met inkomen en uitgaven van inwoners.</p>
					<p>Hoewel de activiteiten van JobHulpMaatje Zoetermeer slechts zijdelings te maken hebben met dit onderwerp, is deze studiemiddag zeker ook interessant voor maatjes. Bij deze word je dan ook van harte uitgenodigd om deel te nemen aan de studiemiddag
					die rond het onderwerp Geldzaken is georganiseerd.</p>
					<p>Tip: deze bijeenkomst is uiteraard ook nuttig als mogelijke uitbreiding van je eigen netwerk als maatje.</p>
					<div style="border: solid 1px blue; padding: 7px; font-style: italic;">
					<table>
						<tr><td>Datum :&nbsp;&nbsp;</td><td>Woensdag 17 november 2021</td></tr>
						<tr><td>Tijdstip :</td><td>Ontvangst vanaf 13:00h</td></tr>
						<tr><td></td><td>Aanvang studiemiddag 13:30h</td></tr>
						<tr><td></td><td>Afsluitende borrel 17:15h</td></tr>
						<tr><td></td><td>Einde studiemiddag 18:00h</td></tr>
						<tr><td>Locatie :</td><td>NH Hotel - Danny Kayelaan 20, 2719 Zoetermeer</td></tr>
						<tr><td>Kosten :</td><td>Deze studiemiddag wordt u kostenloos aangeboden</td></tr>
					</table><br/>
					<p>Wat gaan we doen?</p>
					<p>De dag start met een plenaire bijeenkomst van Roeland van Geuns met het thema: “Waarom is schuldhulpverlening zo ingewikkeld”</p>
					<p>Verder zijn er twee workshoprondes. U kunt aangeven welke workshops u zou willen volgen. Wij proberen zoveel mogelijk rekening te houden met ieders keuze.</p>
					<p>Voorwaarde deelname:</p>
					
					<p>Gezien de huidige corona maatregelen, moeten we je ook vragen om een QR code of negatieve PCR test te overhandigen bij binnenkomst. Zonder dit, kunnen wij u helaas niet toelaten.</p>
					<p>Meld u aan via de onderstaande link:</p>
					
					<p><a href="https://docs.google.com/forms/d/e/1FAIpQLSdOHJxQC4SI0ppqP9sas20r7ygs35Av6P8Z-rqLTfBCNKpkig/viewform?usp=sf_link" target="_new">docs.google.com/forms</a></p>
					<p>Na aanmelding ontvangt u een bevestiging.</p>
					</div>
					';
					

$newsmsg[26] = '<h3 class="bluefont">Nieuwe coronamaatregelen</h3>
					<h5 class="bluefont">3-11-2021</h5>
					<p>Afgelopen dinsdag zijn door de overheid strengere maatregelen genomen tegen de verdere verspreiding van het Corona-virus. De maatregelen gaan in op zaterdag 6 november en
					zullen ook gevolgen hebben voor JobHulpMaatje.</p>
					<p>Zo wordt op veel plaatsen het dragen van mondkapjes weer verplicht, met name in openbare, afgesloten ruimten zoals de bibliotheek/forum en
					andere plekken die we gebruiken zoals ShareBizz en de Kapelaan.</p>
					<p>Verder wordt ook op steeds meer plaatsen vereist dat je voor toegang een geldige QR-code moet kunnen laten zien waaruit blijkt dat je volledig bent gevaccineerd of bent genezen van Covid-19. Je krijgt ook een QR-code als je 
					je 24 uur of korter voor Corona hebt laten testen en een negatieve uitslag daarvan hebt.</p>
					<p>Ons advies? Laat je vaccineren alsjeblieft. Het helpt niet alleen jezelf maar ook alle mensen die dicht bij je in de buurt komen.</p>
					<img src="img/niet-coronatoegangsbewijs-1920.png" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Teams">
					<p>Voor toegang tot de bibliotheek is geen Corona-toegangsbewijs nodig maar voor ShareBizz en de Kapelaan wel. Of wij voor bijeenkomsten in de bibliotheek als een JobGroup ook de QR-code zullen vragen, is
					afhankelijk van de JobGroup-leiding. Deelnemers zullen tijdig op de hoogte worden gebracht.</p>
					';



$newsmsg[25] = '<h3 class="bluefont">Goed nieuws voor Nederland...</h3>
					<h5 class="bluefont">21-10-2021</h5>
					<p>... maar wat zijn de gevolgen voor JobHulpMaatje?</p>
					<p>Op de NRC website staat onderstaand artikel over de werkeloosheidcijfers in Nederland. Die dalen, da\'s goed nieuws natuurlijk. Maar daarmee
					is niet het hele verhaal vertelt. Want er blijven heel veel mensen buiten beeld. Dat zijn de mensen waarop wij ons richten. Lees het hele artikel hier.</p>
					<img src="img/NRC211021.png" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Teams">
					';



$newsmsg[24] = '<h3 class="bluefont">Opnieuw het Streekblad</h3>
					<h5 class="bluefont">10-10-2021</h5>
					<img src="img/IMG_1398.jpeg" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Teams">
					<p>Dit keer besteedt het Zoetermeerse Streekblad van 7 oktober een kort artikeltje aan de nieuwe JobGroup die eind oktober start.</p>
					<p>Let op de onderstaande alinea. Hier wordt het nieuwe adres van de website van JobHulpMaatje Zoetermeer al gebruikt.</p>
					';


$newsmsg[23] = '<h3 class="bluefont">Een nieuwe website voor JobHulpMaatje Zoetermeer</h3>
					<h5 class="bluefont">3-10-2021</h5>
					<!-- <img src="img/microsoftteams-rz_-1200x600-1.png" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Teams"> -->
					<p>De website wordt vernieuwd. In de komende weken zal stap voor stap de oude website worden uitgefaseerd en worden vervangen door een nieuwe.</p>
					<p>Dat zal voor de maatjes van JobHulp Maatje Zoetermeer geen erg grote veranderingen met zich meebrengen omdat zij vrijwel geen gebruik maakten van de (externe) website.</p>
					<p>Toch willen we graag dat zij kennis nemen van de nieuwe website. Dus kijk ernaar alsjeblieft en laat weten wat je ervan vindt. Wat is goed, wat is niet goed, wat mis je, wat is er teveel.</p>
					<p>Lees er meer over op de pagina onder de knop.</p>
					<a class="btn btn-primary" href="pages/bericht20211003_2.php" role="button">De nieuwe website &raquo;</a></p>
					';



$newsmsg[22] = '<h3 class="bluefont">Hoe een werkzoeker z\'n weg weer vond</h3>
					<h5 class="bluefont">3-10-2021</h5>
					<!-- <img src="img/microsoftteams-rz_-1200x600-1.png" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Teams"> -->
					<p>De mensen die wij, als JobHulpMaatje, helpen bij hun zoektocht naar werk, zijn allemaal heel verschillend. Iedere werkzoeker is niet alleen als persoon uniek,
					maar ook wat betreft zijn of haar hulpvraag. En iedere zoektocht van de werkzoeker met een maatje levert een uniek verhaal op. Het zijn deze verhalen
					die ons als maatje sterken in onze overtuiging om anderen te helpen.</p>
					<p>Hier vind je zo\'n verhaal. Over Max die een tijd geleden al eens een JobGroup bij ons volgde en nu werk heeft. Maar hij wil meer. Lees het hele verhaal onder de knop.
					</p>
					<a class="btn btn-primary" href="pages/bericht20211003_1.php" role="button">Het verhaal van Max &raquo;</a></p>
					';


$newsmsg[21] = '<h3 class="bluefont">Maatjesavond, wat is er gezegd</h3>
					<h5 class="bluefont">8-9-2021</h5>
					<div class="container mb-4">
					<div class="row">
						<div class="col p-0 m-0"><img src="fotoos_person/flipbakker.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/jangeerdes.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/jantinebaas.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/janwaaijer.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/johanalebregtse.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/johnzandbergen.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/jokesikking.jpg" width="100%"></div>
					</div>
					<div class="row">	
						<div class="col p-0 m-0"><img src="fotoos_person/pieterhoevers.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/robbertsmit.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/robsmit.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/sjaaksibbing.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/sjanetbeekman.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="fotoos_person/nicovanleeuwen.jpg" width="100%"></div>
						<div class="col p-0 m-0"><img src="" width="100%"></div>
					</div>
					</div>
					<p>Met 13 van de 26 maatjes aanwezig is afgelopen maandag 6 september de eerste fysieke maatjesavond in tijden gehouden. Plaats van delict was de Kapelaan, 
					waar de deelnemers op gepaste afstand van elkaar konden plaatsnemen.</p>
					<p>Op de agenda stonden veel losse punten die een
					voor een aan de orde kwamen. Omdat enkele mensen op het laatste moment verhinderd waren, bleven sommige punten helaas nog wat onderbelicht. Hopelijk gaat dat volgende keer beter.</p>
					<p>Punten van belang om te noemen:</p>
					<ul>
					<li>Als je maatje bent van iemand die geen Jobgroup heeft gevolgd en je wilt LDC-testen gebruiken, dan kun je een emailtje naar Johan sturen.</li>
					<li>JobHulpMaatje Zoetermeer stopt met de proef met het gebruik van het landelijke HVS.</li>
					<li>In de komende maanden worden evaluatiegesprekken met de maatjes gepland. Ze zullen door Johan, Flip, Jan en Joke worden worden afgenomen.</li>
					<li>We stoppen even met het werven van maatjes omdat het aantal aanmeldingen van werkzoekenden terugloopt en dat ligt aan de situatie op de arbeidsmarkt.</li>
					<li>We hebben afscheid genomen van Flip. Hij heeft van het bestuur een hotelovernachting gekregen, voor zijn vrouw en hem.</li>
					</ul>
					<p>Als je nog vragen of opmerkingen hebt, laat het mij weten, via email of via WhatsApp. Kijk op <a href="https://intra.jhmz.nl/faces.php">Wie is Wie</a> voor mijn gegevens.</p>
					<p>Coördinator Maatjes<br/>Joke Sikking</p>
					';


$newsmsg[20] = '<h3 class="bluefont">Landelijke maatjesdag</h3>
					<h5 class="bluefont">2-9-2021</h5>
					<img src="img/microsoftteams-rz_-1200x600-1.png" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Teams">
					<p>Over ruim 2 maanden, op zaterdag 6 november, vindt de 2021 maatjesdag plaats. Ook deze keer zal de meeting online worden georganiseerd zodat het niet alleen weer
					Corona-proof is maar de deelnemers veel reistijd bespaard blijft. Toch zullen veel mensen het persoonlijke contact weer enorm missen. Laten we hopen
					dat het volgend jaar weer wel gezamenlijk op één locatie kan.</p>
					<p>Om deel te kunnen nemen moet je vrijwilliger bij JobHulpMaatje Zoetermeer zijn en je opgeven via het formulier dat je onder de knop vindt. Hier vind je ook de agenda.</p>
					<a class="btn btn-primary" href="https://jobhulpmaatje.nl/2251-2/" target="_new" role="button">Aanmelden Landelijke Maatjesdag &raquo;</a></p>
					';
					
$newsmsg[19] = '<h3 class="bluefont">Agenda maatjesavond 6 september</h3>
					<h5 class="bluefont">31-8-2021</h5>
					<p>Maandag a.s. vindt de maatjesavond plaats. Als jij je nog niet opgegeven heb, kan dat nog steeds via onderstaande knop.<p>
					De agenda is nu bekend. Klik op de agenda-knop.</p>
					<p>We hopen dat zoveel mogelijk mensen erbij zijn. We gaan elkaar sinds lange tijd weer zien. Tot maandag!</p>
					<p>Tot maandag!</p>
					<p><a class="btn btn-primary" href="pages/bericht20210831_1.php" role="button">Bekijk de agenda &raquo;</a></p>
					<p><a class="btn btn-primary" href="#" role="button">Meld je aan &raquo;</a></p>
					<p>PS!: Houd je aan de geldende corona-maaatregelen! Ze zijn nog steeds van kracht.</p>';
	
$newsmsg[18] = '<h3 class="bluefont">Nieuwe ZZP jobgroup</h3>
					<h5 class="bluefont">24-8-2021</h5>
					<img src="img/JHMZwerk-e1629802218626.png" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Knipsel">
					<p>Voorde tweede keer dit jaar start JobHulpMaatje Zoetermeer met een jobgroup voor mensen die nadenken over een baan in dienstverband of een bestaan als zelfstandige.</p> 
					<p>Onder leiding van Johan en Jenny gaan de deelnemers vanaf 24 september aan de slag en hopen ze beter te weten te komen wat voor hen de beste keuze is.</p>
					';

$newsmsg[17] = '<h3 class="bluefont">JobHulpMaatje ambassadeurs</h3>
					<h5 class="bluefont">12-8-2021</h5>
					<img src="img/IMG_1295.jpeg" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Knipsel">
					<p>Samenwerken werkt! Nadat ze de training "Ik Werk In Nederland" met succes en met veel plezier had doorlopen, kwam cursist Rosane de Souza op het idee
					om een taalwandeling te organiseren die door Gilde Samenspraak is uitgezet in Zoetermeer.<p>
					<p>Samen met de andere cursisten uit de iWIN Jobgroup en een paar maatjes van JobHulpMaatje Zoetermeer liep ze de taalwandeling zoals je uit het verslag kunt opmaken.</p>
					<p>De samenwerking met Gilde Samenspraak smaakt naar meer. Hopelijk kunnen in de toekomst hier een vervolg aangeven.</p> 
					';

$newsmsg[16] = '<h3 class="bluefont">iWIN in het Streekblad</h3>
					<h5 class="bluefont">29-7-2021</h5>
					<img src="img/knipsel2.jpg" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Knipsel">
					<p>Zo\'n 2 weken geleden vond de 10de en laatste sessie van de iWIN jobgroup plaats in het Forum. Daar werden de certificaten aan de deelnemers uitgereikt.<p>
					<p>De jobgroup is erg goed ontvangen door de deelnemers en werd hoog gewaardeerd. Maar ook de jobgroupleiders waren erg te spreken over
					de gemotiveerde cursisten en hun inzet. Nu staan ze prominent op pagina 5 van het Zoetermeerse Streekblad.</p>
					<p>Vrijdag 30 juli heeft één van de deelnemers een Taalwandeling georganiseerd en krijgt de jobgroup hiermee een informeel vervolg. De wandeling staat open voor ieder maatje en zijn of haar werkzoekende.
					Misschien dat dit initiatief in de toekomst vaker samen met JobHulpMaatje kan worden georganiseerd. We houden je op de hoogte.</p>
					';

$newsmsg[15] = '<h3 class="bluefont">16 juli afsluiting iWIN jobgroup</h3>
					<h5 class="bluefont">7-7-2021</h5>
					<img src="img/knipsel1.jpg" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Knipsel">
					<p>Op 15 juni j.l. startte JobHulpMaatje Zoetermeer de tweede "Ik Werk In Nederland" jobgroup. </p>
					<p>Inmiddels zijn er 7 ochtenden voorbij en is er hard gewerkt door de deelnemers o.l.v. de jobgroupleiders Johan en Jan G. om zichzelf goed voor de dag te brengen voor de Nederlandse arbeidsmarkt.</p>
					<p>In de laatste 3 workshops worden nog de puntjes op de i gezet en op vrijdag 16 juli a.s. zullen zij een pitch geven over wie ze zijn, wat ze kunnen en wat ze graag willen.
					Wij jobgrouptrainers hopen dat daarbij meer mensen aanwezig zijn zodat ook zij met deze enthousiaste deelnemers kennis kunnen maken. Bij deze nodigen we dan ook graag 
					belangstellenden uit bij deze laatste ochtend van de training aanwezig te zijn. Als je zin hebt, stuur dan een email met je aanmelding m.b.v. de knop hieronder.<p>
					
					<a class="btn btn-primary" href="mailto:johan@jhm-zoetermeer.nl" target="_new" role="button">Stuur email naar Johan &raquo;</a></p>
					
					';

	$newsmsg[14] = '<h3 class="bluefont">Nieuwe Algemeen Coördinator</h3>
					<h5 class="bluefont">2-7-2021</h5>
					<!-- <img src="img/slaapsmurf.png" class="my-2 float-right" style="width: 70%; margin-left: 15px;"> -->
					<img src="fotoos_person/jangeerdes.jpg" class="my-2 float-right float-right" style="width: 20%; margin-left: 15px;" alt="Jan Geerdes">
					<p>In de bestuursvergadering van maandag 28 juni jl. heeft het bestuur het besluit genomen om Jan Geerdes te benoemen tot Algemeen Coördinator, met ingang van 1 september as.</p>
					
					<p>In de tussenliggende periode zullen Jan en Flip samen met de andere coördinatoren werken aan een herverdeling van het takenpakket in het team.</p>
					<img src="fotoos_person/petergabel.jpg" class="my-2 float-left" style="width: 20%; margin-right: 15px;" alt="Peter Gabel">
					<p>Daarbij zal ook een invulling worden gezocht voor de taken van Peter Gabel. Vanwege de aanstaande (vervroegde) pensionering van zijn partner wil hij zijn inzet voor JobHulpMaatje beëindigen. 
					Het bestuur bedankt Peter voor zijn inzet, en zijn bijdrage aan het beschrijven en stroomlijnen van werkprocessen.</p>
					<img src="fotoos_person/flipbakker.jpg" class="my-2 float-right" style="width: 20%; margin-left: 15px;" alt="Flip Bakker">
					<p>Het bestuur bedankt Flip Bakker, die de pionier is geweest en de organisatie heeft gebracht waar deze nu staat. Flip blijft de wekelijkse workshops verzorgen en blijft dus actief als vrijwilliger.</p>
					<p>Het bestuur is blij met Jan Geerdes als nieuwe Algemeen Coördinator, en wenst hem een goede voorbereiding in de komende weken.</p>
					<br/>
					<p>Namens het bestuur,<br/>
					Jan Waaijer,<br/>voorzitter</p>
					
					';
					
					
	$newsmsg[13] = '<h3 class="bluefont">Geen nieuws, goed nieuws?</h3>
					<h5 class="bluefont">28-6-2021</h5>
					<img src="img/slaapsmurf.png" class="my-2 float-right" style="width: 70%; margin-left: 15px;">
					<p>Het is al meer dan een maand geleden dat het vorige bericht op het intranet van JobHulpMaatje werd geplaatst. Als je je afvraagt of de redacteur misschien 
					een beetje in slaap is gesukkeld, dan kan ik hierbij zeggen dat dat niet het geval is. 
					Het komt omdat er gewoon weinig vermeldenswaardig gebeurt bij JobHulpMaatje Zoetermeer in de laatste weken, zo vlak voor de zomer. Alles lijkt z\'n gangetje te gaan.</p>
					<p>Er loopt op dit moment een jobgroup "Ik Werk In Nederland" en de zoektocht naar een nieuwe Algemeen Coördinator loopt ook nog, tot nu toe zonder resultaat. Maar verder 
					is het relatief stil. Het aantal aanmeldingen is zeer beperkt sinds begin dit jaar en lijkt zelfs nog verder af te nemen nu de zomer er aan komt en de lockdown is geëindigd, tijdelijk of niet.</p>
					<p>O ja, om met iets leuks te eindigen: op <strong>maandagavond 6 september a.s.</strong> zal de nieuwe <strong>Maatjesavond</strong> worden georganiseerd. En dit keer, als alle tekenen ons niet bedriegen, komen we allemaal bij elkaar
					en kunnen we weer gezamenlijk onderling bijpraten. In ieder geval nemen we dan ook afscheid van de huidige Algemeen Coördinator Flip Bakker. Gelukkig blijft Flip wel betrokken bij JobHulpMaatje maar op een (veel)
					lager pitje gaat hij dan door. Tijd voor verandering.</p>
					<p>Noteer de datum dus alvast in je agenda. Meer informatie volgt zeker en vast!</p>
					';


	$newsmsg[12] = '<h3 class="bluefont">Het einde van de pandemie. Wat nu?</h3>
					<h5 class="bluefont">24-5-2021</h5>
					<p>Nu het aantal vaccinaties in Nederland in sneltreinvaart stijgt en het aantal besmettingen per week sterk afneemt, rijst de vraag: wat betekent
					dat voor de arbeidsmarkt in z\'n algemeenheid en voor JobHulpMaatje Zoetermeer in het bijzonder?</p>
					<p>Lees de beschouwing van de redactie.</p>
					
					<a class="btn btn-primary" href="pages/bericht20210519_1.php" target="_new" role="button">Verder lezen &raquo;</a>
					';
	

	$newsmsg[11] = '<h3 class="bluefont">Een nieuwe algemeen coördinator</h3>
					<h5 class="bluefont">19-5-2021</h5>
					<p>Beste coördinatoren en maatjes</p>
					
					<p>Recent zijn jullie op de hoogte gesteld van het ontstaan van de vacature
					algemeen coördinator als gevolg van het voorgenomen terugtreden naar een
					bescheiden niveau van Flip Bakker.</p>
					
					<p>De advertentie is gepubliceerd in het Streekblad maar daar is geen reactie
					op gekomen. Daarom willen we nu actief mogelijke kandidaten gaan opzoeken.</p>
					
					<p>Namens het bestuur vraag ik jullie rond te kijken in eigen netwerk en
					vriendenkring om te zien of daar een potentiële kandidaat tussen zit. Als
					dat zo is breng die persoon dan in contact met Flip of met mij, of laat
					één van ons contact zoeken ter verdere oriëntatie. Een wederzijdse verkenning
					kan het begin zijn van iets goeds.</p>
					
					<p>Ik hoop dat jullie rondkijken en wie weet.</p>
					
					<p>Bij voorbaat dank,</p>
					
					<p>Namens het bestuur</p>
					
					<p  class="font-italic">Jan Waaijer</p>
					';

				
	$newsmsg[10] = '<h3 class="bluefont">In the picture</h3>
					<h5 class="bluefont">13-5-2021</h5>
					<p>Het Zoetermeerse Streekblad zet JobHulpMaatje regelmatig in het zonnetje. Dit keer wordt terecht de aandacht gevestigd op het verhaal van Sjanet
					en werkzoekende Rob die zij met succes begeleidde naar een nieuwe baan. Story telling op z\'n best!</p> 
					<img src="img/IMG_0917.jpg" class="my-2 float-right" style="width: 100%; margin-left: 15px;">
					';

	$newsmsg[9] = '<h3 class="bluefont">Masterclass Netwerken Zoetermeer</h3>
					<h5 class="bluefont">13-5-2021</h5>
					<p>Erik Scherder, hoogleraar Klinische Neuropsychologie aan de VU in Amsterdam en bekend van zijn DWDD-colleges op TV, 
						gaf onlangs een lezing over netwerken voor Netwerk Zoetermeer Businessclub. Clubleden Jan Waaijer en Peter Veld vonden het
						de moeite waard om deze lezing met de JobHulpMaatjes te delen.</p>
					<p>De eerste 14 minuten zijn "wachttijd", daarna begint de lezing.</p>
					<p> Zeker in het tweede deel zitten boeiende dingen.</p> 
					<iframe width="560" height="315" src="https://www.youtube.com/embed/zhgZjG-GDFc?start=840" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
					';

	$newsmsg[8] = '<h3 class="bluefont">Werken via een uitzendbureau</h3>
					<h5 class="bluefont">12-5-2021</h5>
					<p>Op 1 juli van 19.30 - 21.00 uur geven 2 recruiters/ intercedenten een online bijeenkomst over werken via het uitzendbureau. Met vragen zoals:</p>
					<ul>
					<li>Hoe werkt werken via een uitzendbureau tegenwoordig?</li>
					<li>Kan een werkzoekende zo binnenlopen met een CV?</li>
					<li>Hoe zorgt een werkzoekende ervoor dat ze gevonden wordt voor een baan?</li>
					<li>Hoe presenteert een werkzoekende zichzelf?</li>
					<li>Welke contractvormen zijn mogelijk?</li>
					<li>Speeddaten? Randstad Boost, is dat ook wat voor ons?</li>
					</ul>
					<p>Allemaal vragen over werken via een uitzendbureau. En natuurlijk is het mogelijk om zelf vragen te stellen.</p>
					
					<p>Het wordt gegeven op donderdagavond 1 juli van 19.30-21.00 uur. Online. Na aanmelding volgt maandag voor de bijeenkomst de link met uitnodiging. 
					Lijkt het je interessant / leuk om deel te nemen? Meld je aan via de onderstaande link. Het kost niets.</p>
					<p  class="font-italic">Marloes Bouwmeester<br/>
					Coordinator servicepunt Jobhulpmaatje</p>
					<a class="btn btn-primary" href="https://docs.google.com/forms/d/e/1FAIpQLSeF0dUEBCJqsAMohlsBvxN51mw4uzCNTZay4_X7ZkmUoRiBlQ/viewform" target="_new" role="button">Meld je aan voor de lezing &raquo;</a>';


	$newsmsg[7] = '<h3 class="bluefont">Humor</h3>
					<h5 class="bluefont">11-5-2021</h5>
					<p>Ik kwam deze cartoon tegen en moest er erg om lachen. Echte zgn. galgenhumor, humor met een \'bite\'.<p>
					<p>Ik wilde \'m jullie niet onthouden.</p>
					<img src="img/argibald_netwerken.jpg" class="my-2 float-right" style="width: 100%; margin-left: 15px;">
					';

	
	$newsmsg[6] = '<h3 class="bluefont">JobHulpMaatje timmert aan de weg</h3>
					<h5 class="bluefont">29-4-2021</h5>
					<img src="img/IMG_0896.jpg" class="my-2 float-right" style="width: 100%; margin-left: 15px;">
					<p>In een advertorial in het Streekblad van 29 april komt veel aan bod. O.a. de vacature van Algemeen Coördinator en de agenda voor de Jobgroups.<p>
					
					';
		


	$newsmsg[5] = '<h3 class="bluefont">Hercertificering voor maatjes</h3>
					<h5 class="bluefont">27-4-2021</h5>
					<!-- <img src="img/nietalleen.jpg" class="my-2 float-right" style="width: 100%; margin-left: 15px;"> -->
					<p>Om als maatje voor JobHulpMaatje te mogen optreden is het vereist dat je de training "JobHulpMaatje" met succes hebt gevolgd. 
					Als bewijs daarvoor krijg je een certificaat van JobHulpMaatje Nederland en mag je als maatje werkzoekenden helpen bij het vinden van nieuw werk.</p>
					<p>Zo\'n certificaat heeft een geldigheidsduur van 3 jaar. Na 3 jaar vervalt dus de inzetbaarheid van een maatje voor JobHulpMaatje.</p>
					<p>Om de geldigheid van het certificaat te verlengen kan een maatje een hercertificeringstraining volgen.</p>
					<p>JobHulpMaatje Zoetermeer is gestart in 2018 met de eerste maatjes. De eerste certificaten vervallen dus dit jaar, in 2021. De volgende mensen wordt nu gevraagd zich te hercertificeren:</p>
					<ul>
					<li>Johan Alebregtse</li>
					<li>Flip Bakker</li>
					<li>Marius Cusell</li>
					<li>Sjaak Sibbing</li>
					<li>Jenny Sulkers</li>
					<li>Peter Veld</li>
					<li>Ton Vermeulen</li>
					<li>John Zandbergen</li>
					<li>Jan Geerdes</li>
					<li>Paula Keun</li>
					<li>Nico van Leeuwen</li>
					<li>Rob Smit</li>
					</ul>
					<h5>Online hercertificeren</h5>
					<p>Hercertificering vindt plaats op zaterdag 22 mei of op donderdag 17 juni, online. Graag ontvang ik van ieder bovengenoemd maatje op welke van genoemde dagen zij beschikbaar zijn hiervoor. Stuur mij vóór 3 mei 
					een antwoord per email. Ik regel dan je deelname met JobHulpMaatje Nederland en houd je op de hoogte.</p>
					<p>Joke Sikking</p>
					
					<a class="btn btn-primary" href="mailto:joke@jhm-zoetermeer.nl" target="_new" role="button">Stuur email naar Joke &raquo;</a></p>
					';
		

		
	$newsmsg[4] = '<h3 class="bluefont">Landelijke publiciteit</h3>
					<h5 class="bluefont">24-4-2021</h5>
					<img src="img/nietalleen.jpg" class="my-2 float-right" style="width: 100%; margin-left: 15px;">
					<p>Omroep de EO besteedt aandacht aan JobHulpMaatje. Aan het woord komen Zoetermeers maatje Chrystal Korving en haar werkzoekende Peggy Altman.</p>
					<p>Je kunt het artikel lezen via de knop. Je kunt ook luisteren naar het programma "Niet alleen" van de EO.</p>
					
					
					<a class="btn btn-primary" href="https://www.eo.nl/artikel/jobhulpmaatje-chrystal-werk-biedt-zoveel-meer-dan-een-maandelijkse-beloning" target="_new" role="button">Ga naar de EO-website &raquo;</a></p>
					';
		

	$newsmsg[3] = '<h3 class="bluefont">Verslag van de maatjesavond</h3>
					<h5 class="bluefont">21-4-2021</h5>
					<p>De maatjesavond was gevuld met "fact & fun". Corrie Buren heeft wederom een verslag gemaakt van de avond. Helaas moeten we het stellen zonder foto\'s of screenshots van de avond.</p>
					
					<p>Mocht iemand van de aanwezigen alsnog een opname hebben van de avond en wil hij/zij  dat delen met de anderen, ik hoor het graag via mijn email.</p>
					<p>Lees met onderstaande knop het verslag.</p>
					<a class="btn btn-primary" href="pages/bericht20210421_1.php" role="button">Lees het verslag &raquo;</a></p>
					<a class="btn btn-primary" href="mailto:jang@jhm-zoetermeer.nl" role="button">Email Jan G. &raquo;</a></p>
					';
		
	$newsmsg[2] = '<h3 class="bluefont">Uitslag van de pubquiz</h3>
					<h5 class="bluefont">21-4-2021</h5>
					<p>De maatjesavond van afgelopen maandag was een geslaagd online evenement. Ondanks de wat tegenvallende vraag naar JobHulpMaatje steun was de stemming uitstekend.</p>
					<p>Onderdeel van de avond was een (korte) pubquiz waarin de teams van 4 personen 20 vragen in 20 minuten beantwoord moesten worden. En dat lukte heel aardig. Wat gelijk de vraag oproept: waren de vragen niet te makkelijk?</p?
					<p>Hoe dan ook, de uitslag van de quiz was als volgt:
					<ul style="list-style-type: none;">
					<li>1. De gorilla\'s en de chimpansees delen de eerste plaats met 18 goede antwoorden. GEFELICITEERD!</li>
					<li>3. De bonobo\'s werden mooi derde met 17 goede anwoorden.</li>
					<li>4. De bavianen sloten met 16 antwoorden nipt aan.</li>
					<li>5. De oerang-oetans sloten, enigszins teleurstellend maar nog wel voldoende ;-), af met een krappe 15 goede antwoorden.</li>
					</Ul>
					<p>Al met al zijn geen van de maatjes echt door het ijs gezakt. We kunnen tevreden zijn over het niveau van triviale kennis van onze vrijwilligers!.</p>
		
					';
			
		
	$newsmsg[1] = '<h3 class="bluefont">Op de voorpagina!</h3>
					<h5 class="bluefont">16-4-2021</h5>
					<p>De aanwas van nieuwe mensen die op zoek zijn naar werk en ons daarbij om ondersteuning vragen loopt al enige maanden achter bij de verwachtingen.</p>
					<p>Deels komt dat waarschijnlijk omdat we lastiger te bereiken zijn, minder zichtbaar in de publieke ruimte. 
					En deels mogelijk ook omdat mensen afwachtender zijn nu de pandemie op z\'n einde lijkt te lopen, wachtend totdat we uit de tunnel zijn.</p>
					<p>Publiciteit is daarom des te belangrijker voor JobHulpMaatje. Er wordt gewerkt aan een nieuwe strategie en nieuwe acties om onze naam verder bekend te krijgen.</p>
					<p>Dat we op de goede weg zijn bewijst bijgaand plaatje. We staan op de voorpagina van het Streekblad van Zoetermeer. Met dank aan Corrie Buren.</p>
					<img src="img/IMG_0865.jpg" class="my-2 float-right" style="width: 100%; margin-left: 15px;">
		
					';
					
	$newsmsg[0] = '<h3 class="bluefont">Maatjesavond 19 april</h3>
					<h5 class="bluefont">14-4-2021</h5>
					<p>Het zijn moeilijke tijden voor JobHulpMaatje en haar vrijwilligers. Coaching en begeleiding gaat toch vaak om het persoonlijke contact dat je opbouwt in samenkomsten en gesprekken met hulpvragers.</p>
					<p>Ook onderling contact hebben is lastig. De lockdown duurt al 4 maanden!</p>
					<p>Gelukkig hebben we toch nog een maatjesavond, al moet het nog een keer via de digitale snelweg. En dit keer hebben we ook voorzien in een luchtige noot. Om de stemming erin te houden zullen we maar zeggen ;-)</p>
					<p>Kijk op de agenda! En heb je je nog niet aangemeld, doe dat dan ook nog even.</p>
					
					<a class="btn btn-primary" href="pages/bericht20210414_1.php" role="button">de agenda &raquo;</a></p>
					<a class="btn btn-primary" href="pages/presence_list200419.php" role="button">aan/af melden &raquo;</a></p>
					';


	return $newsmsg;

}
