<?php

function getMsgs ($number)
{
	$newsmsg = array();

	$newsmsg[22] = '<h3 class="bluefont">Peter Veld in het nieuws</h3>
	<h5 class="bluefont">19-11-2020</h5>
					<p>Gisteren (18-11) is ons bestuurslid Peter Veld gehoord door de parlementaire onderzoekscommissie Toeslagen.</p>
					<img src="img/peterveld_nieuws201118.jpg" class="float-right" style="width: 100%; margin-bottom: 15px;">
					<p>Het was een zeer uitgebreid verhoor waarin Peter kritisch werd bevraagd maar duidelijke antwoorden wist te geven. Het is een ingewikkeld verhaal maar Peter heeft hopelijk geholpen bij onderzoek hoe dit grote probleem is ontstaan en hoe het zo uit de hand is gelopen. Laten wij hopen dat de aanbevelingen er voor zorgen dat problemen die er zijn geweest nooit meer zullen voorkomen. Het menselijk leed is enorm en het mag nooit meer gebeuren. Laten wij hopen dat het verhaal van Peter hieraan heeft bijgedragen.</p>
			';
	

	$newsmsg[21] = '<h3 class="bluefont">Een oproep van het Oranje Fonds</h3>
	<h5 class="bluefont">9-11-2020</h5>
					<p>JobHulpMaatje Zoetermeer heeft zich ook dit jaar weer opgegeven voor de actie "Maatjes gezocht" van het Oranje Fonds.</p>
					<img src="img/OranjeFonds01.png" class="float-right" style="width: 100%; margin-bottom: 15px;">
					<p>Met aandacht op landelijk niveau op radio en TV voor de zoektocht naar maatjes hopen ook wij nieuwe vrijwilligers te kunnen aantrekken.</p>
					<p>De actie start 25 november en duurt 3 weken.</p>
					<p>Wil je meer weten, klik dan op onderstaande knop.</p>
					<p><a class="btn btn-primary" href="pages/bericht20201109_1.php" role="button">Lees de gehele email &raquo;</a></p>
			';
		


	$newsmsg[20] = '<h3 class="bluefont">Grote opkomst bij digitale maatjesdag</h3>
	<h5 class="bluefont">7-11-2020</h5>
					<p>De landelijke maatjesdag die door JobHulpMaatje Nederland werd georganiseerd is druk bezocht. Maar i.p.v. een bruisend samenkomen in Veenendaal werd het een
					iets gestroomlijnder online versie m.b.v. Microsoft Teams.</p>
					<img src="img/maatjesdag1.png" class="float-right" style="width: 100%; margin-bottom: 15px;">
					<p>En dat lukte behoorlijk goed. De opkomst was met ruim 50 mensen voor de camera en achter de microfoon heel goed. Dit aantal werd bereikt tijdens de plenaire
					bijeenkomst die door Ewout Suithoff van JobHulpMaatje Nederland werd voorgezeten.</p>
					<p>Daarna splitste de groep deelnemers zich in verschillende workshopbijeenkomsten.</p>
					<p>Niet voor iedereen was het allemaal even eenvoudig om Teams goed te gebruiken, temeer daar er verschillende versies in omloop zijn. Maar in het algemeen konden de deelnemers goed meedoen in de discussies en workshops.</p>
					<p>Uiteindelijk werd rond 12:30h de bijeenkomst afgesloten. De conclusie was dat er niets boven een bijeenkomst in persona gaat maar dat dit zeker een acceptabel alternatief was als \'in het echt\' niet mogelijk is.</p>
					<img src="img/maatjesdag2.png" class="float-right" style="width: 100%; margin-bottom: 15px;">
			';
		

	$newsmsg[19] = '	<h3 class="bluefont">Nog een advertorial ....</h3>
	<h5 class="bluefont">6-11-2020</h5>
	<img src="img/IMG_0723.jpeg" class="float-left" style="width: 60%; margin-bottom: 15px; margin-right: 15px;
					  -o-transform: rotate(5deg);
					  -webkit-transform: rotate(5deg);
					  -moz-transform: rotate(5deg);
					  position: relative;
					  top: 10px;
					">
					<p>Nu het Forum gesloten is en geïnteresseerden niet in een gesprek aan de balie van JobHulpMaatje kennis kunnen maken, is het des te belangrijker dat we via andere media laten zien wat we kunnen doen.</p>
					<img src="img/IMG_0722.jpeg" class="float-right" style="width: 100%; margin-bottom: 15px;">
					<p>De vorige advertentie was bedoeld voor mensen die, nieuw in Nederland, op zoek zijn naar werk. Deze advertorial (een ingezonden stuk onder redactie van en betaald door de inzender) vertelt over de jobgroup die JobHulpMaatje speciaal voor kleine ondernemers en ZZP\'ers 
					heeft ontwikkeld. Want deze groep heeft het juist in deze Corona-tijd een stuk moeilijker.</p>
					<p>We houden je wederom op de hoogte.</p>
			';

	$newsmsg[18] = '	<h3 class="bluefont">Het Forum/de bibliotheek in Zoetermeer gaat tijdelijk dicht</h3>
	<h5 class="bluefont">4-11-2020</h5>
					<p>Het is niet anders, het Forum van Zoetermeer gaat voor de komende weken, in ieder geval tot 19 november, volledig op slot.</p>
					<img src="img/gesloten corona_0.png" class="float-right" style="width: 100%; margin-bottom: 15px;">
					<p>Dit betekent dat JobHulpMaatje tot die tijd geen activiteiten op locatie kan houden. Alle afspraken zullen worden afgezegd of naar online-afspraken worden omgezet.</p>
					<p>Ook de baliebezetting op elke donderdag in het Forum is daarmee komen te vervallen tot nader order.</p>
					<p>Houdt het intranet in de gaten!</p>
					<p><a class="btn btn-primary" href="https://www.forumzoetermeer.nl" role="button">Naar het Forum &raquo;</a></p>
			';
			
	$newsmsg[17] = '	<h3 class="bluefont">Opnieuw aandacht in de krant</h3>
	<h5 class="bluefont">30-10-2020</h5>
					<p>In het regiokatern van het AD van donderdag 29 oktober wordt aandacht besteed aan JobHulpMaatje.</p>
					<img src="img/jhmAD201029.jpg" class="float-right" style="width: 100%; margin-bottom: 15px;">
					<p>Dit keer gaat het over de jobgroup die JobHulpMaatje op 17 november start voor ZZP\'ers en kleine ondernemers. 
					Zij worden bij het wegvallen van omzet door de Corona-maatregelen extra hard getroffen omdat zij nauwelijks terug kunnen vallen op werkloosheidsuitkeringen.</p>
					<p>Tip: als mensen belangstelling hebben voor ondersteuning door JobHulpMaatje bij het zoeken naar nieuw werk, laat hen bij voorkeur het formulier invullen dat op de website wordt aangeboden.
					Het geeft ons direct meer inzicht in de situatie van de aanvrager en zijn wensen.</p> 
			';

	
	$newsmsg[16] = '	<h3 class="bluefont">Uitslag IT-enquête</h3>
						<h5 class="bluefont">25-10-2020</h5>
						
					<p>De enquête om een beeld te krijgen van IT gebruik binnen JHM Zoetermeer is nu beëindigd.</p>
					<p>De vraag om deze te in te vullen is gesteld aan alle 24 medewerkers van JHMZ. 15 mensen (63%) hebben hier gehoor gegeven, van 9 mensen is geen reactie gekomen.</p>
					<table class="table table-sm table-bordered">
					<thead class="thead-dark">
					<tr><th>Overzicht</th><th>Totaal</th><th>Gereageerd</th><th>Niet-gereageerd</th></tr>
					</thead>
					<tbody>
					<tr><td>Bestuursleden</td><td>3</td><td>1</td><td>2</td></tr>	
					<tr><td>Coördinatoren</td><td>3</td><td>3</td><td>0</td></tr>
					<tr><td>Maatjes</td><td>17</td><td>10</td><td>7</td></tr>
					<tr><td>Support</td><td>1</td><td>1</td><td>0</td></tr>
					</tbody>
					</table>
					
					<p>Op basis van de antwoorden kunnen enkele conclusies worden getrokken. Let op: op basis van alleen de respondenten natuurlijk!</p>
					<ol>
					<li>Iedereen (100%) gebruikt WhatsApp (duhhuh!)</li>
					<li>Ook iedereen gebruikt Microsoft Word. Dat lijkt minder logisch want voor zover ik weet heb je formeel een betaalde licentie nodig om Word te kunnen gebruiken. En dat zou betekenen dat alle 15 respondenten zo\'n licentie hebben, als onderdeel van een MS Office licentie. Klopt dit?</li>
					<li>73% gebruikt een PC, 27%, gebruikt een Mac.</li>
					<li>Maar liefst 80% maakt gebruik van Microsoft Teams. Dat is mooi. Als we er in slagen bij de laatste 20% ook Teams aan de praat te krijgen dan zijn we bij een volgende online-meeting compleet.</li>
					<li>Slechts een enkeling maakt geen gebruik van een smartphone. Maar wel van WhatsApp, ook dat valt op.</li>
					</ol>
					<p>Tot slot:</p>
					<ul>
					<li>Microsoft Office wordt algemeen gebruikt. De vraag is of gebruikers een officiële licentie hiervoor hebben of dat men oude of illegale versies gebruikt. Dit wordt nader uitgezocht.</li>
					<li>Een gezamenlijke cloud-oplossing voor maatjes kan helpen om documenten met elkaar te delen.</li>
					<li>Microsoft Teams wordt al breed gebruikt. Om hier als organisatie samen goed gebruik van te kunnen maken kan een gemeenschappelijke opzet en training erg helpen.</li>
					</ul>
					<p><strong>Alle vragen</strong></p>
					<table class="table table-sm table-bordered">
					<thead class="thead-dark">
					<tr><th>Wat</th><th>Aantal</th><th>%</th></tr>
					</thead>
					</tbody>
					<tr><td>Ik gebruik een Windows-PC of -laptop</td><td>11</td><td>73%</td></tr>
					<tr><td>Ik gebruik een iMac of MacBook</td><td>4</td><td>27%</td></tr>
					<tr><td>Ik gebruik een tablet (iPad of Android)</td><td>9</td><td>60%</td></tr>
					<tr><td>Ik gebruik een telefoon (iPhone of Android)</td><td>13</td><td>87%</td></tr>
					<tr><td>Ik gebruik (nog) iets anders</td><td>1</td><td>7%</td></tr>
					<tr><td>Ik gebruik niets</td><td>1</td><td>7%</td></tr>
					<tr><td>Ik werk met Windows</td><td>12</td><td>80%</td></tr>
					<tr><td>Ik werk met Mac OSX</td><td>7</td><td>47%</td></tr>
					<tr><td>Ik werk met MS Word</td><td>	15</td><td>100%</td></tr>
					<tr><td>Ik werk met MS Excel</td><td>11</td><td>73%</td></tr>
					<tr><td>Ik werk met MS Powerpoint</td><td>11</td><td>73%</td></tr>
					<tr><td>Ik werk met MS Teams</td><td>12</td><td>80%</td></tr>
					<tr><td>Ik maak gebruik van cloud-services (online-opslag van documenten)</td><td>10</td><td>67%</td></tr>
					<tr><td>Ik maak gebruik van SMS (op m\'n telefoon)</td><td>7</td><td>47%</td></tr>
					<tr><td>Ik maak gebruik van WhatsApp (op m\'n telefoon of op m\'n PC)</td><td>15</td><td>100%</td></tr>
					</tbody>
					</table>
			';
	


	$newsmsg[15] = '	<h3 class="bluefont">Reclame in Het Streekblad</h3>
			<h5 class="bluefont">23-10-2020</h5>
			<img src="img/IMG_0707.jpeg" class="float-left" style="width: 60%; margin-bottom: 15px; margin-right: 15px;
							  -o-transform: rotate(-5deg);
							  -webkit-transform: rotate(-5deg);
							  -moz-transform: rotate(-5deg);
							  position: relative;
							  top: 10px;
							">
							<p>Eerder schreven we het al: JobHulpmaatje gaat flink werven via de papieren media. Zoals nu met een paginagrote advertentie in het Zoetermeerse Streekblad.</p>
							<img src="img/IMG_0706.jpeg" class="float-right" style="width: 100%; margin-bottom: 15px;">
							<p>In de komende weken zal blijken hoeveel mensen zich bij JobHulpMaatje gaan melden.</p>
							<p>We houden je op de hoogte.</p>
					';
		
	
	$newsmsg[14] = '	<h3 class="bluefont">Microsoft Teams</h3>
			<h5 class="bluefont">19-10-2020</h5>
			<p>JobHulpMaatje Zoetermeer maakt gebruik van Microsoft Teams om elkaar online te kunnen ontmoeten en te vergaderen met mensen van zowel binnen als buiten de organisatie. Microsoft Teams is gratis te downloaden en te gebruiken. Wil je hier meer over weten, klik op de knop die onderaan dit artikel staat.</p>
			<img src="img/msteams1.png" class="float-right" style="width: 50%; margin-bottom: 15px; margin-right: 15px;">
			
			<p>Het gebruik van Teams kan soms verwarrend overkomen. Dat komt omdat Teams ook deel kan uitmaken van het Microsoft365 pakket dat naast Teams, ook de Microsoft Office programma’s bevat (Word, Excel, Powerpoint, Outlook etc.). 
			Om dat pakket te kunnen gebruiken heb je een licentie nodig. En voor sommige functies in Teams heb je ook zo’n licentie nodig. 
			Deze zijn echter niet noodzakelijk om te kunnen vergaderen met beeld en geluid met andere mensen met een gratis versie van Teams.</p>
			<p>Teams is daarom een goed programma voor gebruik bij online Jobgroups en online coach-gesprekken. Alle partijen moeten dan wel de beschikking hebben over:</p>
			<ul>
			<li>Of een smartphone (Android of Apple)</li>
			<li>Of een tablet (Android of Apple)</li>
			<li>Of een PC (Windows of Mac)</li>
			</ul>
			<p>Als het gebruikte apparaat  van redelijk recente makelij is zal het installeren van een gratis versie van Teams geen problemen moeten opleveren.</p>
			
			<p>Op dit moment is JobHulpMaatje Zoetermeer in gesprek met andere JHM-locaties om te kijken of het handig is om (goedkoop) licenties in te zetten voor het gebruik van Microsoft365. Dus zowel voor bestuursleden, coördinatoren als wellicht ook maatjes. Dat lijkt op het eerste gezicht een goede zet maar het gebruik van het pakket en de omvang is tamelijk complex en niet geheel kosteloos in een organisatie die bestaat uit vrijwilligers die zelfstandig bepalen waarmee ze willen werken. Later hierover meer.</p>
			
			<p>Voor de werkzoekenden geldt dat zij dus altijd de beschikking kunnen krijgen over de gratis versie van Teams.</p>
			
			<p>In dit kader is het ook handig voor JHMZ om te weten hoe de huidige situatie is mbt IT-hulpmiddelen. Vul ajb de enquete in die bovenaan de pagina wordt genoemd.</p>
			
			<p><a class="btn btn-primary" href="https://www.microsoft.com/nl-nl/microsoft-365/microsoft-teams/free" role="button">Naar Microsoft Teams voor nop &raquo;</a></p>
		';
	


	$newsmsg[13] = '	<h3 class="bluefont">Gratis persoonlijk ontwikkeladvies</h3>
			<h5 class="bluefont">15-10-2020</h5>
			<p><strong>Belangrijk bericht voor maatjes,</strong> bespreek dit met je werkzoekenden. Het biedt extra  mogelijkheden aan werkzoekenden die een carrière-switch overwegen. Let op: het vorige budget was snel volgeboekt, dus wacht niet te lang met aanmelden en help elkaar daarbij.</p>
			<p><strong>Vanaf 1 december 2020 gratis persoonlijk ontwikkeladvies. Meld je nu vast aan en start vanaf december!</strong></p>
			<p>Maak gebruik van het kosteloos ontwikkeladvies. Dit ontwikkeladvies is beschikbaar voor (niet) werkenden, flexwerkers en zelfstandigen vanaf 18 jaar en die nog niet de AOW leeftijd hebben. Het ontwikkeladvies bestaat uit 2-3 gesprekken en een arbeidsmarktscan. Er zijn ook mogelijkheden voor kosteloze online scholing vanuit hetzelfde overheidsprogramma. Op de website onder de knop vind je actueel nieuws vanuit de Rijksoverheid over NL leert door.</p>
			<p><strong>Werkzoekenden</strong> zijn hierover ook via de whatsapp-groepen geïnformeerd: neem contact op met je maatje/jobgroupleider.</p>
			<p><a class="btn btn-primary" href="https://www.hoewerktnederland.nl/werknemen/leren-en-ontwikkelen/loopbaanadvies/werkzoekenden" role="button">Naar de website &raquo;</a></p>
		';
	
	$newsmsg[12] = '	<h3 class="bluefont">Nieuwe maatregelen i.v.m. Covid-19</h3>
			<h5 class="bluefont">14-10-2020</h5>
			<p>Gisteravond heeft het bestuur van JHM-Z naar aanleiding van de persconferentie over de nieuwe Covid-maatregelen op 13 oktober 2020, besloten om alle fysieke bijeenkomsten van JHM voor de komende 4 weken stil te leggen. Het gaat dan om de lopende JobGroup, de wekelijkse Workshops, en de geplande maatjes-hercertificeringsbijeenkomst op 12 november. We gaan de mogelijkheden bezien om de uitvoering van JobGroup en Workshop digitaal te continueren.</p>
			<p>Over twee weken bekijken we de situatie opnieuw. Daarom gaan de voorbereidingen voor de bijzondere JobGroups iWIN en ZZP - geplande start op 17 november as. - voorlopig gewoon door.</p>
			<p>Wat betreft de 1 op 1 maatjescontacten laten we de beslissing bij de maatjes zelf: fysiek op 1,5m of digitaal. Wel vragen we om - vooral in deze onzekere tijden - het contact met de werkzoekenden te onderhouden.</p>
			<p>De digitale landelijke JHM-dag gaat op 7 november as. gaat wel door.</p>
		';

	$newsmsg[11] = '	<h3 class="bluefont">Nieuws in de lokale pers</h3>
					<h5 class="bluefont">11-10-2020</h5>
					<img src="img/IMG_0701.jpeg" class="float-right" style="width: 60%; margin-bottom: 15px;  
					  -o-transform:rotate(5deg);
					  -webkit-transform:rotate(5deg);
					  -moz-transform:rotate(5deg);
					  position:relative;
					  top:-10px;
					">
					<p>Dat JobHulpMaatje flink aan de weg timmert wordt nog eens geïllustreerd in de gratis Zoetermeerse weekkrant "Het Streekblad" van 8 oktober jl.</p>
					<img src="img/IMG_0700.jpeg" class="float-right" style="width: 100%; margin-bottom: 15px;">
					<p>In de komende  tijd kun je meer verwachten in de media.</p>
				';

	$newsmsg[10] = '	<h3 class="bluefont">Zaterdag 7-11, landelijke (digitale) maatjesdag</h3>
						<h5 class="bluefont">9-10-2020</h5>
						<p>De landelijke maatjesdag is door alle Corona-perikelen veranderd van opzet. Geen samenkomen dit jaar in Veenendaal, maar een digitale bijeenkomst via Microsoft Teams.</p>
						<img src="img/microsoftteams-rz_-1200x600-1.png" class="float-right" style="width: 100%; margin-bottom: 15px;">
						<p>Hiervoor wordt de zaterdagochtend gereserveerd van 9:30h tot 12:30h. Er zijn verschillende onderdelen gepland. Meer daarover kun je lezen op de website van JobHulpMaatje Nederland. Je kunt je daar ook inschrijven voor digitale workshops.</p>
						<p>Belangrijk is natuurlijk dat je Microsft Teams hebt geïnstalleerd en weet hoe je het moet gebruiken. Het programma heeft een gratis versie en die is voldoende. Als je vragen hebt, stel ze in het forum! Daar is het voor.</p>
						<p><a class="btn btn-primary" href="https://jobhulpmaatje.nl/aanmelden-digitale-landelijke-dag/" role="button">Lees meer en meld je aan &raquo;</a></p>
					';
	
	$newsmsg[9] = '		<h3 class="bluefont">Verslag van de bestuursvergadering van maandag 5 oktober</h3>
						<h5 class="bluefont">7-10-2020</h5>
						<p>We hebben als bestuur van JobHulpMaatje Zoetermeer een goede gewoonte: bij toerbeurt openen de deelnemers met een korte meditatie. Deze keer was het Jan Waaijer, hij las uit de memoires van Ruud Lubbers: de tijden – dat zijn wij. We staan niet buiten de tijd, de actualiteit zijn wij zelf.</p>
						<p>We volgen een standaard-agenda, de JHM-activiteiten: maatjes, werkzoekenden, jobgroup/workshop, ondernemers, organisatie, ondersteuning/ict, financiën, pr/communicatie. Vanochtend hebben we die punten vooral bezien in het licht van het bestuurlijk overleg deze week met wethouder Margreet van Driel. We hebben daarvoor besproken hoe we JHM het beste kunnen positioneren. En wat de maatschappelijke meerwaarde is:</p>
							<ol>
							<li>Financieel: besparing uitkeringen (2019: 8 uit bijstand, 11 uit ww/wia)</li>
							<li>Individueel: werkzoekenden naar werk</li>
							<li>Individueel: maatschappelijke inzet vrijwilligers (maatjes)</li>
							<li>Collectief: bijdrage aan Participatie-doelstelling Zoetermeer</li>
							<li>Last but not least: preventie schuldenproblematiek</li>
							</ol>
							<p>Als vrijwilligersorganisatie – zonder personeelslasten – dus een groot rendement!</p>
							</p>
					';
	
	$newsmsg[8] = '		<h3 class="bluefont">GAK-pilot en succesvolle uitstroom</h3>
						<h5 class="bluefont">7-10-2020</h5>
						<p>Op de online-maatjesavond heeft Flip aangegeven dat we heel succesvol hebben gescoord in de zgn. GAK-pilot Over de Brug. Samen met 3 andere JHM-locaties (Leiden, Oss, Zwolle) hebben we daarvoor ingetekend: mensen niet alleen maar beter bemiddelbaar maken, maar daadwerkelijk de brug over helpen naar werk. We mochten daarvoor in het afgelopen jaar:</p>
						<ul>
							<li>40 werkzoekenden aanmelden waarmee we een JHM-traject in gingen.
							Daarvoor kregen we een vergoeding van € 250 per persoon.</li>
							<li>Daarboven mochten we nog eens 10 extra werkzoekenden aanmelden, maar dan zonder die startbijdrage.</li>
							<li>Uit die groep van 50 aangemelde werkzoekenden, mochten we er ca. 10 weer afmelden als die aantoonbaar succesvol naar werk of opleiding werden bemiddeld.</li>
							<li>In die afmelding zijn we als Zoetermeer zeer succesvol geweest! Omdat de andere JHM-locaties mogelijk met minder afmeldingen zouden komen, hebben we als Zoetermeer die ruimte gevuld. Uiteindelijk met 15 succesvol uitgestroomde werkzoekenden.</li>
							<li>Zeven voor de ‘hoofdprijs’ € 1500, voor een contract > 6 mnd. en > 16u/week.</li>
							<li>Zes voor € 1000 voor een kleiner contract < 6 mnd / uitzendcontract</li>
							<li>Twee voor € 500 voor een doorstroom naar een reguliere vervolgopleiding.</li>
						</ul>
							<p>Aantoonbaar: dat wil zeggen dat we daarvoor de contracten, inschrijfbewijzen moesten overleggen. We hadden geen kandidaten voor de categorie: gestart als ZZP/ondernemer (€1000), tenminste niet in die groep van 50 aangemelden. 
							</p>
						<h5>Meer succesvolle uitstroom</h5>
							<p>Maar bij die 15 uit 50 is het echt niet gebleven wat betreft onze resultaten. We hebben in 2018 de eerste 12 werkzoekenden aan een baan geholpen. In 2019 waren dat er meer: 32 werkzoekenden stroomden succesvol uit naar werk. In 2020 gaan we de coronacrisis merken: we zitten nu op 17 succesvolle uitstromers; een verdubbeling zit er waarschijnlijk niet meer in.</p>
							<p>Binnenkort zullen we de lijst van maatjes en gekoppelde werkzoekenden actualiseren. Daarbij zullen we ook de status van de uitgestroomden in beeld brengen. Dan krijgt ons werk ook meer gezicht (in meervoud).</p>							
					';
	
	$newsmsg[7] = '		<h3 class="bluefont">Regels voor het gebruik van het Forum Zoetermeer</h3>
						<h5 class="bluefont">1-10-2020</h5>
						<p>Regelmatig maken we gebruik van het Forum in Zoetermeer voor afspraken en bijeenkomsten. Onlangs zijn de regels hiervoor aangescherpt. Lees in de email waar je op moet letten dan.</p>
						<p><a class="btn btn-primary" href="pages/bericht20201001_1.php" role="button">Naar de email &raquo;</a></p>
					';
		
	$newsmsg[6] = '		<h3 class="bluefont">Maandag 5-10, Maatjesavond</h3>
						<h5 class="pinkfont">30-9-2020, aanvulling</h5>
						<p class="pinkfont">Na rijp beraad heeft het bestuur besloten dat de geplande bijeenkomsten normaal doorgang kunnen vinden. Wel wordt aangeraden mondkapjes te gebruiken 
							en de 1,5 meter afstand heel goed in de gaten te houden. Het Forum is gewoon open en bereikbaar.</p>
							<p class="pinkfont">Als je vragen hebt of opmerkingen, laat ze weten in de WhatsApp-groep van JobHulpMaatje. Houdt dit in de gaten!</p>
							<p class="pinkfont">Ook heel belangrijk is dat je laat weten of je deel gaat nemen of juist niet. We kunnen hier dan rekening meehouden bij het nemen van afdoende maatregelen.</p>
						<p>Op maandag a.s. is weer een Maatjesavond gepland. Op deze avond presenteert het bestuur de laatste stand van zaken rond JobHulpMaatje en werpt een blik op de toekomst. Uiteraard komen ook andere zaken aan de orde.</p>
						<p>Echter, op dit moment is nog niet helemaal duidelijk wat de gevolgen zijn van de nieuwste Corona-maatregelen van de regering van maandag 28-9. Het ziet er naar uit dat we formeel bij elkaar mogen komen maar dat besluit
							dient wel genomen te worden. Wat is toegestaan is niet altijd automatisch wat verstandig is.</p>
						<p>Een definitieve beslissing volgt zo snel mogelijk!</p>
						<p><a class="btn btn-primary" href="agenda.php" role="button">Naar de agenda &raquo;</a></p>
					';
	
	$newsmsg[5] = '		<h3 class="bluefont">Computers enzo, wat hebben we nodig?</h3>
						<h5 class="bluefont">29-9-2020</h5>
						<p>Voor een vrijwilligersorganisatie als JobHulpMaatje zonder vaste woon- of verblijfplaats is het belangrijk om de onderlinge contacten zo goed mogelijk te faciliteren. Hierbij spelen de digitale middelen een grote rol. Zeker als je ook rekening houdt met de Corona-pandemie waardoor het voorlopig onduidelijk blijft of echt samenkomen toegestaan is.</p>
						<p>Een onvermijdelijke bijkomstigheid is dat medewerkers zelf bepalen welke digitale spullen ze gebruiken voor hun werkzaamheden. Het is immers hun eigendom. Daarom wllen we graag weten hoe wij, als stichting, iedereen zo goed mogelijk kunnen helpen om die middelen in te zetten voor JobHulpMaatje. Daarom vind je hier een kleine enquete om inzicht te krijgen wat er al is en wat we kunnen doen om te helpen.</p>
						<p>Bij deze dus graag even wat van je tijd om de vragen te beantwoorden. Alvast bedankt!</p>
						<p><a class="btn btn-primary" href="enquete.php" role="button">Naar de enquête &raquo;</a></p>
					';
	
	$newsmsg[4] = '		<h3 class="bluefont">JobHulpMaatje nieuwsbrieven</h3>
						<h5 class="bluefont">20-9-2020</h5>
						<p>Regelmatig maakt bestuurslid van JHM Zoetermeer Peter Veld een nieuwsbrief met de laatste nieuwtjes voor iedereen die geïnteresseerd is in de stand van zaken rond JobHulpMaatje, zowel lokaal als nationaal.</p>
						<p>Kijk hier om te lezen wat er gaande is en was bij het ter perse gaan van de nieuwsbrieven.</p>
						<p><a class="btn btn-primary" href="nieuwsbrief.php" role="button">Naar de nieuwsbrieven &raquo;</a></p>
					';
	
	$newsmsg[3] = '		<h3 class="bluefont">Workshop: Solliciteren nu – Netwerken</h3>
						<h5 class="bluefont">11-9-2020</h5>
						<p>Iedere week worden er workshops gegeven voor werkzoekenden waar maatjes bij aanwezig zijn. Als je meer wilt weten hierover, klik dan op onderstaande knop.</p>
						<img src="img/schema_workshopdeelname.png" class="float-right" style="width: 50%;">
						<p><a class="btn btn-primary" href="procedure.php" role="button">Workshops? &raquo;</a></p>
					';				
	
	$newsmsg[2] = '		<h3 class="bluefont">Intranet voor JobHulpMaatje Zoetermeer</h3>
						<p>JobHulpMaatje Zoetermeer is een vrijwilligersorganisatie. De mensen die zich inzetten voor de stichting doen dat allemaal op vrijwillige basis en meestal ook voor een beperkte tijd van de week. 
						JobHulpMaatje is ook een virtuele organisatie, dus zonder eigen kantoor of andere werkruimte. De mensen zien en spreken elkaar alleen op afspraak, dus meestal alleen als er een zekere noodzaak voor is. 
						Om die reden is het des te belangrijker dat alle medewerkers van JobHulpMaatje Zoetermeer toch een gezamenlijke en publiek afgesloten ruimte voor zichzelf beschikbaar hebben.</p>
						<p>Het intranet, waar je nu bent, is die ruimte.</p>
						<p>Belangrijk om te weten: het intranet is een besloten website. Niet vindbaar op Google, zonder toestemming niet toegankelijk. Er is geen aanmeldprocedure. Inlogggevens worden verstrekt door de ICT-coördinator in overleg met bestuur en andere coördinatoren.</p>
					';
	$newsmsg[1] = '		<h3 class="bluefont">Corona</h3>
						<p>We leven op dit moment in onzekere tijden door de pandemie die wereldwijd heeft toegeslagen. Alle media berichten gretig over alle vervelende zaken die door het Corona-virus op ons af dreigen te komen.</p>
						<p>Zo wordt er o.a een flinke toename in het aantal werkzoekenden verwacht en dat kan betekenen dat JobHulpMaatje mogelijk drukke tijden tegemoet gaat.</p>
						<p>Wat deze en andere ontwikkelingen voor de stichting betekenen, kun je hier lezen.
					';
	
	$newsmsg[0] = '		<h3 class="bluefont">Wat kun je verwachten?</h3>
						<p>Het intranet wordt, zoals alles hier, op vrijwillige basis ontwikkeld. Hoogstens worden eventuele onkosten vergoed zolang deze binnen de perken blijven. Gelukkig is er op het internet veel gratis voorhanden.</p>
						<p>Hoewel niets zeker is, is het de bedoeling het intranet uit te breiden met o.a. een agenda-overzicht en een forum voor vragen en antwoorden. Andere suggesties zijn van harte welkom. <a href="mailto:jang@jhm-zoetermeer.nl">Laat het weten en email!</a></p>
					';
	return $newsmsg;
}
