<?php

function getMsgs ($number, $naam)
{
$newsmsg = array();

$newsmsg[40] = '<h3 class="bluefont" id="bouke">Wethouder Bouke Velzen bezoekt Maatjesavond 4 juli</h3>
				<h5 class="bluefont">23-6-2023</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/boukevelzen.jpg" class="figure-img img-fluid" alt="bouke">
 				</figure>
				<p>Onze feestelijke maatjesavond van 4 juli ter  gelegenheid van het eerste lustrum van JobHulpMaatje Zoetermeer zal worden bijgewoond door wethouder Bouke Velzen.</p>
				<p>Bouke heeft vijf jaar geleden namens de Kerken de overeenkomst ondertekend waarmee JobHulpMaatje kon starten. Hij staat dus aan de basis van JHMZ. En nu is hij sinds een jaar onze wethouder die onder meer over werk in Zoetermeer gaat.</p> 
				<p>Dus twee goede redenen om hem uit te nodigen en mooi dat hij ook wil komen. 
				Bouke zal het eerste uur van 20.00-21.00 bijwonen.</p>
				';


$newsmsg[39] = '<h3 class="bluefont" id="maatjesavond3">Ons eerste lustrumviering</h3>
				<h5 class="bluefont">20-6-2023</h5>
				<p>Enige dagen geleden nodigden wij alle JobHulpMaatjes van de afdeling Zoetermeer per email uit voor het bijwonen van de volgende maatjesavond.</p>
				<h5 class="text-center">Dinsdag 4 juli 2023</h5>
				<p>Deze avond wordt, zoals jullie al eerder in een uitnodigingsmail hebben kunnen lezen, extra bijzonder omdat we niet alleen terugblikken op de bereikte resultaten. We richten ook ons blik vooruit. Wat gaat de toekomst ons brengen?</p>
				<p>De agenda staat volledig in de email.</p>
				<p>Alle maatjes zijn uiteraard van harte welkom. Klik op de knop om aan te geven of je komt.</p>
				<p><a class="btn btn-primary" href="pages/presence_list230704.php" role="button">Jubileumavond aan/afmelden &raquo;</a></p>
				<br/>
				<p style="font-style: italic;">Jij bent maatje. Zou je alvast willen nadenken over de vragen bij de “Minutenwals”?  Het gaat erom dat je in enkele zinnen (in ca. 1 minuut) aangeeft wat jou het meest is opgevallen. Een sprekende anekdote mag ook! De bedoeling is dat alle reacties samen kleur geven aan ons JobHulpMaatje.</p>
				';


$newsmsg[38] = '<h3 class="bluefont" id="rollen">Wie doet wat?</h3>
					<h5 class="bluefont">12-5-2023</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
					<img src="img/verbaasd.jpg" class="figure-img img-fluid" alt="verbaasd">
 					</figure>
					<p>Op de maatjesavond is uitgelegd welke mensen bepaalde rollen hebben binnen JobHulpMaatje Zoetermeer.</p>
					<p>Onder de knop vind je een toelichting.</p>
					<p><a class="btn btn-primary" href="pages/bericht20230512_2.php" role="button">Rolverdeling &raquo;</a></p>
					';

$newsmsg[37] = '<h3 class="bluefont" id="maatjesavond3a">Verslag maatjesavond</h3>
					<h5 class="bluefont">12-5-2023</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
					<img src="img/together.jpg" class="figure-img img-fluid" alt="together">
					 </figure>
					<p>Op de derde maatjesavond werd druk gewerkt aan de transactionele analyse van maatjes met werkzoekenden.</p>
					<p>Het bestuur liet zien wat zich op dit moment afspeelt op de arbeidsmarkt en wat dat voor JobHulpMaatje Zoetermeer betekent.</p>
					<p>Voor een compleet verslag klik je op de knop hieronder.</p>
					<p><a class="btn btn-primary" href="pages/bericht20230512_1.php" role="button">Verslag derde maatjesavond &raquo;</a></p>
					';


$newsmsg[36] = '<h3 class="bluefont" id="maatjesavond3">Derde maatjesavond nieuwe stijl</h3>
					<h5 class="bluefont">1-5-2023</h5>
					<p>De derde maatjesavond komt eraan, en wel op woensdagavond 10 mei.</p>
					<p>Teken je nu in voor de avond.</p>
					<!-- <p><a class="btn btn-primary" href="pages/presence_list230510.php" role="button">Maatjesavond aan/afmelden &raquo;</a></p> -->
					';


$newsmsg[35] = '<h3 class="bluefont" id="maatjesavond2">Tweede maatjesavond nieuwe stijl</h3>
					<h5 class="bluefont">15-3-2023</h5>
					<p>De tweede maatjesavond komt eraan, en wel op maandagavond 27 maart.</p>
					<p>Teken je nu in voor de avond.</p>
					<!-- <p><a class="btn btn-primary" href="pages/presence_list230327.php" role="button">Maatjesavond aan/afmelden &raquo;</a></p> -->
					';
					

$newsmsg[34] = '<h3 class="bluefont" id="jaarverslag">Hoe was 2022 voor JobHulpMaatje Zoetermeer?</h3>
					<h5 class="bluefont">10-3-2023</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
					<img src="img/jaarverslag2022.jpg" class="figure-img img-fluid" alt="jaarverslag 2022">
					<figcaption class="figure-caption">Jaarverslag voorpagina</figcaption>
					 </figure>
					<p>Beweren dat 2022 een bijzonder jaar was, is inmiddels een achterhaalde uitspraak. Want het is al het zoveelste \'bijzondere\' jaar op rij.</p>
					<p>Waar in de voorgaande jaren Corona een grote stempel drukte op onze activiteiten en op de wijze waarop we de dingen deden, is in het afgelopen jaar weer
					alles veranderd. Dit jaar lag voor JobHulpMaatje Zoetermeer de nadruk op de vele mensen die door oorlogsgeweld hun land moesten verlaten en in Nederland onderdak zochten. Ook zij wilden aan de slag. Lees het jaarverslag hoe dat ging.</p>
					<p><a class="btn btn-primary" href="https://jobhulpmaatjezoetermeer.nl/nieuws.php" role="button">Naar het jaarverslag 2022 &raquo;</a></p>
					';


$newsmsg[33] = '<h3 class="bluefont" id="maatjesavond1">Eerste maatjesavond nieuwe stijl</h3>
					<h5 class="bluefont">27-1-2023</h5>
					<p>Een NIEUW jaar, nieuwe kansen! Zoals al in een email is uitgelegd, is er dit jaar een serie van maatjesavonden gepland.</p>
					<p>De eerste is al binnenkort, nl. op woensdag 8 februari. Plaats delict is het Stadhuis dit keer. Let op!: We zitten aan de Stamtafel met z\'n allen. Wel graag om 8 uur binnen zijn, anders sta je voor een gesloten deur.</p>
				    <p>Teken je nu in voor de avond.</p>
					<!-- <p><a class="btn btn-primary" href="pages/presence_list230208.php" role="button">Maatjesavond aan/afmelden &raquo;</a></p> -->
					';




$newsmsg[32] = '<h3 class="bluefont" id="bvelzen">In gesprek met de wethouder</h3>
					<h5 class="bluefont">14-12-2022</h5>
					<p>Met het aantreden van een nieuwe gemeenteraad en een nieuw college van Burgemeester en Wethouders, is het altijd raadzaam om de contacten met gemeente goed te onderhouden.</p>
					<p>Op de dag van de maatjesavond hebben enkele bestuursleden rond de tafel gezeten met Bouke Velzen (ChristenUnie - SGP), wethouder voor o.a. Armoedebestrijding en Sociale Zaken,
					om de banden weer eens aan te halen met één van de belangrijkste stakeholders van onze stichting.</p>
					<p>Lees het verslag onder de knop.</p>
					<p><a class="btn btn-primary" href="pages/bericht20221214_1.php" role="button">Gespreksverslag &raquo;</a></p>
					';




$newsmsg[31] = '<h3 class="bluefont" id="maatjesavond">Wat te doen op de maatjesavond</h3>
					<h5 class="bluefont">10-12-2022</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
					<img src="img/de-kapelaan.jpg" class="figure-img img-fluid" alt="De Kapelaan">
					<figcaption class="figure-caption">Vergadercentrum De Kapelaan</figcaption>
 					</figure>
					<h4>Aanvulling: de agenda voor de avond</h4>
					<p>Woensdag a.s. is het zover. De agenda voor de komende maatjesavond is als volgt:</p>
					<ol>
					<li>Opening en mededelingen</li>
					<li>Stand van zaken m.b.t. Jobhulpmaatje (Jan Waaijer)</li>
					<li>Jos Borsboom gedragsdeskundige stelt zich voor en daagt ons uit</li>
					<li>Pauze (15 min)</li>
					<li>IWIN jobgroups (Flip Bakker)</li>
					<li>Terugkoppeling landelijke Maatjesdag (Peter Veld)</li>
					<li>Wat en hoe gaan we het doen volgend jaar (Marius e.a.)</li>
					<li>Sluiting en aansluitend eindejaarsborrel</li>
					</ol>
					<p>Zoals gezegd, we starten om 20:00h en de locatie is nu definitief in de Kapelaan.</p>
					<p>Als je nog niet hebt aangegeven of je komt of niet, doe dat ajb dan nu. Bij het invullen van de aanmeldingslijst lees je hoe je dat doet.
					<!-- <p><a class="btn btn-primary" href="pages/presence_list221214.php" role="button">Maatjesavond aan/afmelden &raquo;</a></p> -->
					';




$newsmsg[30] = '<h3 class="bluefont" id="maatjesavond">Laatste maatjesavond van het jaar</h3>
					<h5 class="bluefont">3-12-2022</h5>
					<p>2022 loopt ten einde. En het was een bewogen jaar, in vele opzichten.</p>
					<p>Op woensdagavond 14 december kijken we gezamenlijk terug op het jaar om te zien hoe JobHulpMaatje het ervan heeft afgebracht. En zeggen we wat over de toekomst.</p>
					<p> En last, but not least, is er voldoende gelegenheid om elkaar weer eens te zien en te spreken.</p>
					<p>De agenda volgt nog (let op je email) en de locatie zal waarschijnlijk de Kapelaan zijn.</p>
					<p>Wij stellen het erg op prijs als je erbij bent. Laat het weten via de presentielijst die je onder bijgaande knop vindt.</p>
					<p>Hopelijk tot 14 december!</p>
					<!-- <p><a class="btn btn-primary" href="pages/presence_list221214.php" role="button">Maatjesavond aan/afmelden &raquo;</a></p> -->
					';



$newsmsg[29] = '<h3 class="bluefont" id="pilot">Nieuwe maatjes gezocht</h3>
					<h5 class="bluefont">21-10-2022</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
  					<img src="img/maatjeadv.jpg" class="figure-img img-fluid" alt="advertentie">
  					<figcaption class="figure-caption">Gemaakt door Corrie Buren</figcaption>
 					</figure>
					<p>Dit voorjaar hadden we de campagne om nieuwe werkzoekers enthousiast te maken voor begeleiding door JobHulpMaatje. Dat bleek een lastige opdracht in een arbeidsmarkt 
					die overspannen is door te veel werkaanbod en te weinig beschikbare mensen.</p>
					<p>De groep werkzoekenden werd echter al snel ruimschoots aangevuld met mensen die hun land ontvlucht waren onder moeilijke omstandigheden en in Nederland werden opgevangen. Deze groep nieuwe Nederlanders 
					maakt gretig gebruik van de begeleiding naar werk die JobHulpMaatje kan bieden. Werk is er genoeg en met de juiste inzet en coaching van onze maatjes maken zij een veel grotere kans op een betaalde baan.</p>
					<p>Dit najaar staat nu in het teken van het werven van nieuwe vrijwilligers. Mensen die voldoende vrije tijd hebben om de nieuwe werkzoekers bij te staan in hun zoektocht. Lees de advertentie die deze week
					verscheen in het Zoetermeerse Streekblad. Weet jij mensen die belangstelling zouden kunnen hebben? Geef ze een zetje en wie weet, worden ze je collega-vrijwilliger bij JobHulpMaatje Zoetermeer.</p>';


$newsmsg[28] = '<h3 class="bluefont" id="pilot">Landelijke maatjesdag</h3>
					<h5 class="bluefont">8-10-2022</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
  					<img src="img/maatjesdagamersfoort.jpg" class="figure-img img-fluid" alt="amersfoort">
  					<figcaption class="figure-caption">Hier komen we samen in Amersfoort</figcaption>
 					</figure>
					<p>Na enkele jaren is het weer mogelijk. Maatjes uit het hele land kunnen elkaar weer ontmoeten op locatie.</p>
					<p>Dit jaar vindt de Landelijke Maatjesdag plaats in Amersfoort op zaterdag 5 november. En iedereen die als vrijwilliger werkt voor JobHulpMaatje is uitgenodigd.</p>
					<p>Kom je ook? Of wil je meer weten? Meld je dan aan en klik op onderstaande knop.</p>
					<!-- <p><a class="btn btn-primary" href="https://jobhulpmaatje.nl/landelijke-dag/" role="button">Maatjesdag 5 november &raquo;</a></p> -->';


$newsmsg[27] = '<h3 class="bluefont" id="afsluiting">iWin 22-2 voor AZC weer groot succes</h3>
					<h5 class="bluefont">6-10-2022</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
  					<img src="img/iWIN22-2.jpg" class="figure-img img-fluid" alt="azc groep iWIN 2">
  					<figcaption class="figure-caption">De deelnemers met links Flip en rechts Ton</figcaption>
 					</figure>
					<p>Opnieuw werden onder vakkundige leiding van Flip Bakker en Ton Vermeulen een flink aantal Nederlandse Nieuwkomers voorbereid om de Nederlandse arbeidsmarkt te betreden.</p>
					<p>Bovenstaand verslag in het Streekblad laat dat in volle glorie zien.</p>';


$newsmsg[26] = '<h3 class="bluefont" id="pilot">Verslag van het bestuur</h3>
					<h5 class="bluefont">30-9-2022</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
  					<img src="img/bestuursvergadering.jpg" class="figure-img img-fluid" alt="bestuur">
  					<figcaption class="figure-caption">Het bestuur in zitting</figcaption>
 					</figure>
					<p>Afgelopen 28 september vergaderde de stuurgroep van JobHulpMaatje Zoetermeer. Klik op de knop en lees het verslag.</p>
					<p><a class="btn btn-primary" href="pages/bericht20220930_1.php" role="button">Naar het verslag &raquo;</a></p>';


$newsmsg[25] = '<h3 class="bluefont" id="maatjesavond">Maatjesavond, over de toekomst</h3>
					<h5 class="bluefont">30-8-2022</h5>
					<p>Je las het al in het vorige bericht, in het bestuursverslag. Op maandagavond 19 september zijn alle vrijwilligers welkom op de tweede maatjesavond van dit jaar.</p>
					<p>Wie nieuwsgierig is naar wat de toekomst van JobHulpMaatje voor jou betekent is van harte welkom om te luisteren naar de plannen en mee te praten over je eigen rol hierbij.</p>
					<p>Dit alles kun je doen onder genot van eten en drinken dat wordt verzorgd door Saskia Koerselman met hulp van anderen (neem ik aan).</p>
					<p>Het is prettig als je met de intekenlijst laat weten of je komt of niet. Klik op onderstaande knop hiervoor. We zien je graag op 19 september.</p>
					<!-- <a class="btn btn-primary" href="pages/presence_list220919.php" role="button">Maatjesavond aan/afmelden &raquo;</a></p> -->
					';

$newsmsg[24] = '<h3 class="bluefont" id="pilot">Verslag van het bestuur</h3>
					<h5 class="bluefont">30-8-2022</h5>
					<p>Afgelopen 25 augustus werd het nieuwe "seizoen" voor JobHulpMaatje Zoetermeer afgetrapt door het bestuur. Saskia Koerselman, Peter Veld en Jan Waaijer bespraken de komende koers nu de hele wereld maar in het bijzonder de arbeidsmarkt aan grote veranderingen onderhevig is.</p>
					<p>Wat dat betekent voor de toekomst van de stichting en voor alle vrijwilligers lees je in grote lijnen terug in het bestuursverslag. Klik hiervoor op de knop.</p>
					<p><a class="btn btn-primary" href="pages/bericht20220830_1.php" role="button">Naar het verslag &raquo;</a></p>';
					
$newsmsg[23] = '<h3 class="bluefont" id="pilot">Maatjes voor Binnenbaners</h3>
					<h5 class="bluefont">30-8-2022</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
					  <img src="img/logoBB.svg" class="figure-img img-fluid" alt="Binnenbaan">
					 </figure>
					<p>De pilot die we samen met de Binnenbaan op poten hebben gezet, gaat nu heel snel van start. De eerste kandidaten hebben zich al aangemeld en kunnen worden gekoppeld aan een maatje. En daarvoor hebben nu maatjes nodig die de kandidaten willen begeleiden.</p>
					<p>Daarom bij deze een oproep. Wie heeft tijd en is bereid een BB-kandidaat onder haar of zijn hoede te nemen? Als jij dat ziet zitten, laat het dan weten aan Joke. Stuur haar dan een korte emailtje met daarin wat je eisen (bv beschikbaarheidstijden) en wensen (bv een beetje matchende achtergrond) zijn. Joke gaat dan, samen met Marius, puzzelen wie met wie een passend duo kan zijn die samen op zoek gaan naar de mogelijkheden naar werk, betaald of niet.</p>
					<p>Aarzel dus niet. Klik op bijgaande button en email Joke.</p>
					<p><a class="btn btn-primary" href="mailto:joke@jhm-zoetermeer.nl" role="button">Email Joke &raquo;</a></p>';
					
$newsmsg[22] = '<h3 class="bluefont" id="pilot">Pilot met Binnenbaan van start</h3>
					<h5 class="bluefont">15-8-2022</h5>
					<p>In de zomer is doorgewerkt aan het opzetten van een pilot met Binnenbaan. Deze is erop gericht dat JobHulpMaatje Zoetermeer  mensen met een grote afstand tot de arbeidsmarkt gaat begeleiden. Afgesproken is dat JobHulpMaatje met de deelnemers een intake doet en dat zij op basis daarvan worden toegewezen aan een Maatje ter begeleiding. Eerder was al gebleken, dat het starten van een JobGroup met deze deelnemers niet eenvoudig is. Daarom is nu gekozen voor individuele begeleiding. Het staat daarbij JobHulpMaatje vrij om aanvullend samen met de deelnemers af te spreken dat zij ook aan groepsactiviteiten van JobHulpMaatje deelnemen. Maar er komt dus geen JobGroup voor alleen “binnenbaners”. Voor de begeleiding van elke deelnemer is vier maanden uitgetrokken, waarna eventueel vervolgafspraken gemaakt kunnen worden.</p>
					<p>De intake door JobHulpMaatje Zoetermeer en de matching met een Maatje zal gedaan worden door Marius Cusell en Joke Sikking. De eerste vier deelnemers zijn al aangemeld. Gestreefd wordt naar een pilot van 10 deelnemers. En er is voorzien in evaluatie. Het document bevat de pilotbeschrijving, zoals die door Binnenbaan in overleg met JobHulpMaatje is opgesteld. Peter Veld is contactpersoon voor Binnenbaan voor de aanpak en evaluatie.</p>
					<p>Lees hier het plan dat de werkgroep hierover opstelde.</p>
					<p><a class="btn btn-primary" href="pages/bericht20220815_1.php" role="button">Naar het plan &raquo;</a></p>';

$newsmsg[21] = '<h3 class="bluefont" id="notitie">Notitie van JobHulpMaatje Landelijk</h3>
					<h5 class="bluefont">14-8-2022</h5>
					<p>JobHulpMaatje is een organisatie in beweging. In een wereld waarin heel veel zaken heel snel veranderen is ook JobHulpMaatje Nederland zich aan het bezinnen op een vernieuwde aanpak.</p>
					<p>Lees hier de notitie die het bestuur van JobHulpMaatje Landelijk hierover opstelde.</p>
					<p><a class="btn btn-primary" href="pages/bericht20220814_1.php" role="button">Naar de notitie &raquo;</a></p>';

$newsmsg[20] = '<h3 class="bluefont" id="afsluiting">iWin voor AZC succesvol</h3>
					<h5 class="bluefont">24-6-2022</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
  					<img src="img/iwin2022.jpg" class="figure-img img-fluid" alt="azc groep">
  					<figcaption class="figure-caption">De deelnemers met hun certificaat</figcaption>
 					</figure>
					<p>Na 10 dagdelen waarin de nieuwe Nederlanders hard hebben gewerkt om zo goed mogelijk voor de dag te komen, werden de certificaten uitgereikt.</p>
					<p>Vele maatjes hebben aan het succes meegewerkt. Lees er meer over in het verslag.</p>
					<p><a class="btn btn-primary" href="pages/bericht20220624_1.php" role="button">Naar het verslag &raquo;</a></p>
					<p><a class="btn btn-primary" href="https://jobhulpmaatjezoetermeer.nl/nieuws.php" role="button">Naar het nieuws op de publieke website &raquo;</a></p>';

$newsmsg[19] = '<h3 class="bluefont" id="afsluiting">Mooie afsluiting campagne</h3>
					<h5 class="bluefont">17-6-2022</h5>
					<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
					  <img src="img/IMG_2065.jpeg" class="figure-img img-fluid" alt="opkomst">
					  <figcaption class="figure-caption">Goede opkomst</figcaption>
					 </figure>
					<p>De bijeenkomst zit erop. Met zo\'n kleine 30 deelnemers was de opkomst heel behoorlijk. Ook de diversiteit van de vertegenwoordigende organisaties was flink.</p>
					<figure class="figure float-left" style="width: 30%; margin-right: 15px;">
					  <img src="img/IMG_2036.jpeg" class="figure-img img-fluid" alt="opkomst">
					  <figcaption class="figure-caption">Peter</figcaption>
					 </figure>
					<p>Het succes is voor het overgrote deel te danken aan de inzet van Peter Veld die de hele campagne "Een Faire Kans Op Werk" heeft opgezet en gecoördineerd.</p>
					<figure class="figure float-right mt-2" style="width: 70%; margin-left: 15px;">
					  <img src="img/IMG_2089.jpeg" class="figure-img img-fluid mt-2" alt="Paula">
					  <figcaption class="figure-caption">Paula</figcaption>
					 </figure>
					
					<p>Paula Keun verbond de verschillende onderwerpen en sprekers met humor aan elkaar en hield het tempo erin. Dat was ook nodig want regelmatig ontstonden er levendige discussies tussen de panelleden onderling en met het publiek.
					De onderwerpen leefden duidelijk bij de toehoorders en aan het eind van de middag was algemeen de conclusie dat dit naar meer smaakte. Meer discussie, meer samenwerking. Hopelijk pakt iemand dit op en gaat er mee aan de slag.</p>
					<figure class="figure float-left" style="width: 70%; margin-right: 15px;">
					  <img src="img/IMG_2067.jpeg" class="figure-img img-fluid" alt="Patrick">
					  <figcaption class="figure-caption">Patrick Verhoef, de Binnenbaan</figcaption>
					 </figure>
					<p>Een inhoudelijk verslag houd je tegoed van de organisatoren van de partnerbijeenkomst. Die valt wat later in je emailbox.</p>';
			
$newsmsg[18] = '<h3 class="bluefont" id="lintjes">Partnerbijeenkomst</h3>
					<h5 class="bluefont">12-5-2022</h5>
					<img src="img/winkelstraat.jpg" class="my-2 float-left" style="width: 100%;" alt="winkelstraat">
					<p>Op donderdag 16 juni sluit JobHulpMaatje Zoetermeer haar publiciteitscampagne af met een bijeenkomst waar wij en onze partners gezamelijk praten over 
					samenwerking om mensen in Zoetermeer 
					die, ondanks de huidige krappe arbeidsmarkt, toch maar moeilijk aan het werk komen, beter te kunnen helpen.</p>
					<p>Ook de inbreng van maatjes is daarbij van belang en daarom is iedere vrijwilliger van JobHulpMaatje uitgenodigd ook aanwezig te zijn en mee te doen aan het gesprek.</p>
					<p>Kom ook op 16 juni!</p>
					<p><a class="btn btn-primary" href="pages/bericht20220512_1.php" role="button">lees meer over de Partnerbijeenkomst &raquo;</a></p>
					<p><a class="btn btn-primary" href="pages/presence_list220616.php" role="button">aanmelden Partnerbijeenkomst &raquo;</a></p>';

$newsmsg[17] = '<h3 class="bluefont" id="lintjes">Uitbreiding</h3>
					<h5 class="bluefont">4-5-2022</h5>
					<p>Nu de publiciteitscampagne al vier weken loopt en vrijwel niemand nog over Corona praat kun je verwachten dat het ook weer begint te bruisen bij JobHulpMaatje. Maar gezegd moet, dat is slechts ten dele waar.
					Het klopt dat er meer mensen zich aanmelden voor ondersteuning van ons. Het zijn nog geen grote aantallen maar wel meer dan in de eerste maanden van dit jaar.
					<p>Deels komt dit omdat de samenwerking met de Binnenbaan, waarover we al enige maanden in gesprek zijn, nog vorm begint te krijgen. Binnenkort start er een pilot-JobGroup met deelnemers die op voordracht van de Binnenbaan
					zich gaan oriënteren op, in eerste instantie, vrijwilligerswerk.
					</p>
					<img src="img/IMG_1854.jpeg" class="my-2 float-right" style="width: 100%;" alt="Grietje wordt gedecoreerd">

					<p>
					Ook Grietje, de echtgenote van Marius Cusell, viel de eer ten deel om een lintje opgespeld te krijgen wegens haar vele verdiensten voor de samenleving.
					</p>
					<p>JobHulpMaatje Zoetermeer feliciteert beiden met deze koninklijke onderscheiding.</p>
';


$newsmsg[17] = '<h3 class="bluefont" id="lintjes">Het heeft de koning behaagd....</h3>
					<h5 class="bluefont">27-4-2022</h5>
					<img src="img/IMG_1865.jpeg" class="my-2 float-left" style="width: 100%;" alt="Flip met lintje">
					<p>... dat Flip Bakker, man van het eerste uur bij JobHulpMaatje Zoetermeer, een lintje kreeg voor alles wat hij heeft gedaan voor de samenleving. Gisteren, in de Stadschouwburg,
					heeft de burgemeester van Zoetermeer de medaille uitgereikt, in het bijzijn van Flip\'s echtgenote Marianne. Hij is vanaf vandaag lid van de Orde van Oranje-Nassau.</p> 
					<p>\'s-Morgens was Flip nog, zoals elke dinsdagochtend, vol goede moed begonnen aan de workshop. 
					Maar kort daarna kwam Peter Veld langs en hij heeft hem als begeleider vervangen zodat Flip met Marianne mee kon, naar de Stadschouwburg. Hij wist van niets, had zelfs geen vermoeden. Totdat hij 
					plaats moest nemen op een stoel op het podium.
					</p>
					<img src="img/IMG_1854.jpeg" class="my-2 float-right" style="width: 100%;" alt="Grietje wordt gedecoreerd">

					<p>
					Ook Grietje, de echtgenote van Marius Cusell, viel de eer ten deel om een lintje opgespeld te krijgen wegens haar vele verdiensten voor de samenleving.
					</p>
					<p>JobHulpMaatje Zoetermeer feliciteert beiden met deze koninklijke onderscheiding.</p>
';


$newsmsg[16] = '<h3 class="bluefont" id="eersteworkshop">Eerste workshop goed bezocht!</h3>
					<h5 class="bluefont">20-4-2022</h5>
					<img src="img/IMG_1788.jpeg" class="my-2 float-left" style="width: 40%; margin-right: 15px;" alt="Eerste Workshop">
					<p>Maar liefst 10 werkzoekenden kwamen naar de workshop ‘DE JOBGROUP - MIJN NETWERK’.</p>
					<p>Johan nam op enthousiaste wijze, met een interactieve sessie, de deelnemers mee in de inhoud van het programma van de JobGroup sessies. 
					Hij liet de deelnemers zien dat het programma uit zeven thema’s bestaat, waarin werkopdrachten, presentaties, oefeningen en thuiswerkopdrachten zijn verwerkt. 
					Johan zoomde in op het thema ‘hoe vind ik een baan’. 
					Samen met de deelnemers werd de sollicitatie piramide kort besproken en werd het verschil zichtbaar hoe een werkgever zoekt en hoe een werkzoekende zoekt. </p>
					<img src="img/IMG_1581.jpeg" class="my-2 float-right" style="width: 40%; margin-left: 15px;" alt="Johan Alebregtse">
					<p>Hiermee werd een heel mooie aftrap gegeven van de reeks van workshops die op <a href="agenda.php">de agenda</a> staat voor de campagne. We kijken uit naar die van volgende week dinsdag!</p>
';



$newsmsg[15] = '<h3 class="bluefont" id="tussenevaluatie">De kop is eraf</h3>
					<h5 class="bluefont">18-4-2022</h5>
					<figure class="figure">
  					<img src="img/campagneaffiche.png" class="figure-img img-fluid" alt="campagneaffiche">
  					<figcaption class="figure-caption">Campagne affiche</figcaption>
					</figure>
					<p>De pubiciteitscampagne voor JobHulpMaatje Zoetermeer startte op maandagavond 11 april met de introductie van de agenda voor de maatjes. In de raadszaal van het gemeentehuis werd door Peter Veld en door Flip Bakker uitgelegd
					wat er de komende tijd wordt gedaan om zoveel mogelijk mensen die werl willen en zoeken, te bereiken en voor te lichten.</p>
					<p>Op donderdag 14 april verscheen in het Zoetermeerse Streekblad de flyer (zie bericht hiervoor) paginagroot als advertentie. Het Streekblad heeft een oplage van 53.800 exemplaren. Dat betekent dat de gratis lokale krant bij vrijwel 
					alle huishoudens en bedrijven door de brievenbus op de mat valt.</p>
					<p>De advertentie bevatte veel informatie. O.a. de agenda voor de workshops die de komende maanden worden gegeven, over de komende JobGroups
';





$newsmsg[15] = '<h3 class="bluefont" id="campagneaffiche">De campagne affiche</h3>
					<h5 class="bluefont">12-4-2022</h5>
					<figure class="figure">
  					<img src="img/campagneaffiche.png" class="figure-img img-fluid" alt="campagneaffiche">
  					<figcaption class="figure-caption">Campagne affiche</figcaption>
					</figure>	
					';




$newsmsg[14] = '<h3 class="bluefont" id="maatjesavond">Maatjesavond: campagnestart 2022!</h3>
					<h5 class="bluefont">26-3-2022</h5>
					<p>Binnenkort starten we de publiciteitscampagne onder de titel "Een Faire Kans Op Werk". Er is veel te doen en we hebben de hulp nodig van zoveel mogelijk maatjes.</p>
					<p>Daarom organiseren we een speciale bijeenkomst om goed uit te leggen aan alle maatjes wat we willen en wat we gaan doen om dat te bereiken: meer bekendheid in Zoetermeer en omgeving!</p>
					<figure class="figure">
					  <img src="img/commissiezaal-stadhuis-forum.jpg" class="figure-img img-fluid" alt="trouwzaal Zoetermeer">
					  <figcaption class="figure-caption">De Commissiezaal annex trouwzaal van Zoetermeer</figcaption>
					</figure>	
					<p>Op maandagavond 11 april vanaf 19:00h komen we bij elkaar in de <del>Commissiezaal/trouwzaal</del> B&W vergaderkamer van het Forum. We zorgen voor drinken en een hapje. 
						En vervolgens bespreken we met elkaar wat er zoal op agenda staat en wat iedereen kan bijdragen aan een succesrijke campagne.</p>
					<p>Uiteraard rekenen we op je om JobHulpMaatje weer op de kaart van Zoetermeer te zetten nu de Corona-pandemie uitgedoofd lijkt. Schrijf je in voor de meeting met onderstaande knop!</p>
					<p>En, o ja. Als je iemand kent die misschien ook wil helpen als JobHulpMaatje, geef dat dan door aan één van de coördinatoren. Email naar <a href="mailto: coordinatoren@jhm-zoetermeer.nl">coordinatoren@jhm-zoetermeer.nl</a>.
					<p>Wij nemen eerst contact met jou op en overleggen dan hoe we verder gaan met iemand die geïnteresseerd is.</p>
					<!-- <a class="btn btn-primary" href="pages/presence_list220411.php" role="button">Maatjesavond aan/afmelden &raquo;</a> -->
					';


$newsmsg[13] = '<h3 class="bluefont" id="campagne2021">Een faire kans op werk</h3>
					<h5 class="bluefont">24-3-2022</h5>
					<h4>Publiciteitscampagne 2021</h4>
					<figure class="figure">
					  <img src="img/fairekans.png" class="figure-img img-fluid" alt="fairekans">
					</figure>
					<p> Onder de titel "een faire kans op werk" start JobHulpMaatje Zoetermeer dit voorjaar een publiciteitscampagne. Dankzij een eenmalige extra financiële bijdrage van <a href="https://www.kansfonds.nl" target="_new">het Kansfonds</a>
					hebben we de ruimte om de komende maanden flink aan de weg te timmeren om meer mensen te kunnen helpen aan de slag te komen.<p>
					<p>Maar behalve geld hebben we vooral ook de energie en inzet van alle maatjes van JobHulpMaatje Zoetermeer nodig. We hebben <a href="pages/bericht20220325.php">een uitgebreide agenda</a> opgesteld met allerlei activiteiten in de maanden april, mei en juni.<p>
					<p>We starten met een speciale maatjesbijeenkomst waarin we uitleggen wat we gaan doen, wat we willen bereiken en wat we aan jullie willen vragen. En we hopen dan dat je op de een of andere manier bij wil dragen aan het succes 
					van de campagne!</p>
					<p>De activiteitenagenda vind je op <a href="pages/bericht20220325.php">deze pagina</a>. Bekijk deze goed en kijk of je er iets tussen vindt dat je aanstaat en waar je bij betrokken wilt zijn. En laat het ons dan ook weten!</p>
					<p>Aan het eind van de campagne hebben we een partnerbijeenkomst gepland. Op die bijeenkomst willen we graag de banden aanhalen met alle organisaties die voor ons op de een of andere manier belangrijk zijn. En dat zijn jullie ook! Dus welliccht zien we je daar ook verschijnen!</p>
					<p>De campagne eindigt weer met een maatjesbijeenkomst waarin terugkijken op alles wat we gedaan hebben en of het een succes is geworden. Dat laatste hopen we natuurlijk van harte. Laten we ons best doen en met z\'n allen onze schouders eronder zetten.</p>
					';


$newsmsg[12] = '<h3 class="bluefont" id="stapregeling">Bestrijd de energiearmoede, volg een workshop</h3>
					<h5 class="bluefont">10-3-2022</h5>
					<p>Ingezonden mededeling<br/>door Piet Goeyenbier</p>
					<div style="border: solid 1px blue; padding: 7px;" class="font-italic">
					<p><strong>Workshop energie besparen in huis en voucher t.b.v. gratis energiebesparende maatregelen</strong></p>
					<figure class="figure">
					  <img src="img/Plaatje-workshop-energie-besparing.jpeg" class="figure-img img-fluid" alt="energieworkshop">
					</figure>
					<p>Als we niet oppassen lopen onze energierekeningen enorm op. Naast de "gratis" maatregelen zijn er eenvoudige energiebesparende materialen te koop zoals bijvoorbeeld radiatorfolie, deurveer en buisisolatie. Deze maatregelen zorgen er voor dat je minder energie verbruikt en toch evenveel warmte in huis hebt.</p>
					<p>Juist deze simpele bespaartips voor thuis worden uitgelegd tijdens deze workshop. Bovendien zijn er voor mensen met lage inkomens die in een slecht geïsoleerde woning wonen vouchers vanuit de gemeente Zoetermeer beschikbaar. Aan het einde van de workshop krijgt de deelnemer deze voucher mee. Met die voucher kunnen energiebesparende materialen gratis aangeschaft worden.</p>
					<p>Is dit iets voor jou? Meld je dan aan via de website <a href="https://www.Zoetermeerbespaart.nl" target="_new">www.zoetermeerbespaart.nl</a>. Hier meld je je aan voor bijvoorbeeld een van de workshops die op woensdagochtend 16-3 en woensdag 23 maart plaatsvinden bij Piëzo aan de Teldersrode 25 in Buytenwegh. Van 9.30 tot ca 11.00 uur.</p>
					<p>Via de website www.zoetermeerbespaart.nl is er keuze uit meer tijdstippen en locaties waar deze energie besparingsworkshops gegeven worden!
					Meld u aan voor zo\'n workshop, doen! Het is duurzaam, want u bespaart op uw energieverbruik en helpt ook de energierekening minder hoog te laten worden.</p>
					</div>
					';


$newsmsg[11] = '<h3 class="bluefont" id="stapregeling">Leer meer over de STAP-regeling</h3>
					<h5 class="bluefont">27-2-2022</h5>
					
					<h2>14-3-2022 AFGELAST! Wegens te weinig belangstelling</h2>
					<p>Vanaf 1 maart 2022 wordt een nieuwe overheidsregeling van kracht, nl. de STAP-budgetregeling.</p>
					<p>In het kort: STAP-budget is een nieuwe vergoeding voor scholing en staat voor <a href="https://www.rijksoverheid.nl/onderwerpen/leven-lang-ontwikkelen/leven-lang-ontwikkelen-financiele-regelingen/stap-budget" target="_new">Stimulering van de ArbeidsmarktPositie</a>. Met dit budget kun je je positie op de arbeidsmarkt verbeteren. Je kunt een vergoeding van maximaal € 1.000 per jaar aanvragen om te gebruiken voor scholing. Deze vergoeding vervangt de huidige belastingaftrek voor studiekosten bij de inkomstenbelasting.</p>
					<p>Maar wat betekent dat voor jou, als maatje? En wat kan het voor je hulpvrager betekenen?</p>
					Belangrijk is in ieder geval dat er een beperkt totaal budget per jaar beschikbaar is voor de aanvragers. Dus als je er gebruik van wilt maken is enige haast geboden.</p>
					<img src="img/bht_elise.png" class="my-2 float-right float-right" style="width: 100%;" alt="buildinghumantalent">
					<p>JobHulpMaatje Zoetermeer heeft Elise Burger van Building Human Talent bereid gevonden om in een online sessie van een uur uit te leggen hoe je de regeling voor jezelf en voor anderen kunt inzetten. 
					Op <strong>woensdagavond 16 maart van 19:30h tot ongeveer 21:00h</strong> zal Elise alles uitleggen en evt. vragen beantwoorden.</p>
					<p>Schrijf je in via de aanmeldlijst met de knop hieronder. Aanmelden kan tot zaterdag 12 maart. Als er voldoende aanmeldingen zijn volgt daarna een link waaarmee je de Teams-sessie kunt volgen op je computer, tablet of smartphone.</P>
					<!-- <a class="btn btn-primary" href="pages/presence_list220316.php" role="button">aanmelden STAP presentatie &raquo;</a></p> -->
					';



$newsmsg[10] = '<h3 class="bluefont" id="nieuwjaarsbijeenkomst">Verlate nieuwjaarsbijeenkomst</h3>
					<h5 class="bluefont">4-2-2022</h5>
					<p>Eindelijk kan het weer. We mogen en kunnen bij elkaar komen om elkaar een hart onder de riem te steken voor 2022. Weliswaar met een flinke vertraging maar op donderdag 17 februari komen we bijeen in de Kapelaan.</p>
					<p>Hieronder volgt de oorspronkelijke aankondiging:</p>
					<div style="border: solid 1px blue; padding: 7px;" class="font-italic">
					<p>Ook het jaar 2021 is weer een bijzonder jaar geworden, het tweede jaar op rij. Het virus heeft dit jaar grote gevolgen gehad voor de samenleving, voor de arbeidsmarkt en voor JobHulpMaatje.</p>
					</p>En het Corona-virus is nog niet klaar met ons allemaal. Kijk maar om je heen en je weet het: ook 2022 wordt niet zoals het ooit vroeger was.</p>
					<p>Maar dit alles is natuurlijk geen reden om bij de pakken neer te zitten. JobHulpMaatje Zoetermeer heeft, zo goed en zo kwaad als het ging, ook in 2021 goed werk verricht. Exacte cijfers heb ik nog niet maar 
					we mogen weer best trots zijn op onszelf en op wat we bereikt hebben. Helaas zit een klein feestje op dit moment er even niet in. We stellen dat uit tot een later moment als de situatie flink verbeterd is.</p>
					<p>Wat we echter wel graag willen doen is op een gepaste wijze het nieuwe jaar aftrappen. Bijvoorbeeld met een kleine nieuwjaarsreceptie waarop we kunnen toasten op 2022.</p>
					<figure class="figure">
  					<img src="img/de-kapelaan.jpg" class="figure-img img-fluid" alt="De Kapelaan">
					</figure>
					<p>We houden daarom de bijeenkomst in de Kapelaan in de Dorpsstraat. Geplande tijd is van 17:00 tot 19:00 uur. Er zal eem warm en koud hapje klaar staan en ook een drankje.</p>
					<p>En we houden ons natuurlijk aan de dan geldende Corona-maatregelen.</p>
					<img src="img/vuurkorf.jpg" class="my-2 float-right float-right" style="width: 20%; margin-left: 15px;" alt="vuurkorf">
					</div>
					<p>Het is prettig als je met de intekenlijst laat weten of je komt of niet. Klik op onderstaande knop hiervoor. We zien je graag op 17 fevruari en hopen dat we met z\'n allen een goed jaar tegemoet gaan.</p>
					<a class="btn btn-primary" href="pages/presence_list220113.php" role="button">receptie aan/afmelden &raquo;</a></p>
					';



$newsmsg[9] = '<h3 class="bluefont" id="fotoshoot">Fotoshoot voor JobHulpMaatje</h3>
					<h5 class="bluefont">27-1-2021</h5>
					<p>JobHulpMaatje Nederland heeft een professionele fotograaf gevraagd foto\'s te nemen voor gebruik bij eigen publicaties, ook voor lokale stichtingen. Het doel is om minder afhankelijk zijn van de bekende standaard stockfoto\'s.
					Daarom de volgende oproep:</p>
					<div style="border: solid 1px blue; padding: 7px;" class="font-italic">
					<p>Beste vrijwilligers,</p>
					 
					<p>Via de Nieuwe Gevers hebben we een fotograaf tot onze beschikking die realistische foto’s gaat maken van onze werkzaamheden bij JobHulpmaatje. Foto’s in een JobGroup, maatjestraject, close-up foto’s … van alles wat. In eerste instantie wilden we daar werkzoekenden voor benaderen maar later kwamen we met het idee om de fotoshoot in scene te zetten met onze eigen vrijwilligers.</p>
					<p>De foto’s worden gebruikt voor promotie op social media, website, nieuwsbrieven etc. Wie vindt het leuk om hier aan mee te werken? De fotoshoot zal een paar uur duren en in februari plaatsvinden. We houden rekening met de geldende corona maatregelen. We vragen vrijwilligers uit Zoetermeer, Leiden, Gouda en Waddinxveen. De fotoshoot zal ook in deze regio plaatsvinden.</p>
					 
					<p>Lijkt je dit leuk en wil je meewerken, geef je op bij jouw coordinator. Later zal een datumprikker worden rondgestuurd om een datum te prikken.</p>
					 
					<p>Met vriendelijke groet,</p>
					 
					<p>Marloes Bouwmeester</p>
					</div><br/>
					<p>Heb je interesse om hieraan mee te doen? Geef je dan op en stuur een email naar JanG. Het is ook een mooie gelegenheid om met maatjes van andere locaties in contact te komen.
					Als er voldoende animo voor is wordt m.b.v. een Datumprikker.nl een afspraak gepland.</p>
					<p>Stuur een reactie vóór vrijdag 4 februari!</p>
					<a class="btn btn-primary" href="mailto:jang@jhm-zoetermeer.nl" role="button">stuur een email naar Jan &raquo;</a></p>
					';



$newsmsg[8] = '<h3 class="bluefont" id="workshops streekblad">Workshops in het Streekblad</h3>
					<h5 class="bluefont">14-1-2022</h5>
					<p>De JobHulpMaatje workshops worden, ook in deze barre tijden, nog steeds iedere dinsdag in de Bibliotheek verzorgd door Flip Bakker. Juist in tijden dat er te weinig animo is voor JobGroups, is deze activiteit 
					bijzonder belangrijk voor de werkzoekenden die wat hulp nodig hebben.</p>
					<p>Het Streekblad van 13 januari toont Zoetermeer waar het om draait bij JobHulpMaatje: Mensen helpen die werk zoeken. Helaas ontbreekt een bijpassende foto en heeft de redactie teruggegrepen op een oude foto die ze nog beschikbaar hadden.</p>
					<img src="img/IMG_1666.jpeg" class="my-2 float-right" style="width: 100%; margin-left: 15px;" alt="Workshops Streekblad">
					';



$newsmsg[7] = '<h3 class="bluefont" id="jgtrainingg">JobGroup-trainer worden</h3>
					<h5 class="bluefont">10-1-2022</h5>
					<p>Het geven van een JobGroup-training is één van de leukste activiteiten voor vrijwilligers die we bij JobHulpMaatje hebben. Je geeft je kennis en ervaring door aan zeer gemotiveerde mensen die graag aan de slag willen op de Nederlandse arbeidsmarkt.</p>
					<img src="img/jobhulpmaatje.jpg" class="my-2 float-right" style="width: 100%; margin-left: 15px;" alt="JobGroup">
					<p>JobHulpMaatje Zoetermeer doet dat alle enige jaren, met succes. En we verwachten dat het in de toekomst eerder drukker wordt dan rustiger. Daarom de vraag aan ieder maatje: wie wil opgeleid worden tot JobGroup-trainer? Als trainer word je minimaal 1 keer per jaar ingezet als trainer voor een JobGroup. Een JobGroup bestaat uit 7 of 10 dagdelen (ochtenden of middagen) en wordt meestal gegeven in het Forum/Bibliotheek van Zoetermeer. Een training geef je ook altijd met z\'n tweeën. Je staat er dus nooit alleen voor. ;-)</p>
					<p>Vrijdag 28 januari start een nieuwe training voor toekomstige JG-trainers. Als je interesse hebt, kun je je <a href="https://jobhulpmaatje.nl/aanmelden-trainingen/?deelnametype=Maatjestraining&locatie=Online" target="_new">hier</a> inschrijven. Of geef je naam door aan <a href="mailto:joke@jhm-zoetermeer.nl">Joke</a> of <a href="mailto:jang@jhm-zoetermeer.nl">Jan</a>. Dan zorgen zij voor verdere aanmelding. Doe dat dan wel graag vóór 15 januari a.s. Na afloop ben je een gecertificeerd JobHulpMaatje JobGroup-trainer.</p>
					<p>Een volgende training vindt plaats in mei van dit jaar. Uiteraard is dat ook een mogelijkheid om opgeleid te worden. Laat het weten bij je coordinator ajb.</p>
					';



$newsmsg[6] = '<h3 class="bluefont" id="dubbelslag">Het JobHulpMaatje schoolplein</h3>
					<h5 class="bluefont">28-12-2021</h5>
					<p>JobHulpMaatje Zoetermeer is een vrijwilligersorganisatie. En helaas zien wij, de vrijwilligers, elkaar slechts zelden. Er is weinig gelegenheid, zeker onder de huidige omstandigheden, met elkaar koffie te drinken, met elkaar bij te praten, te lachen en te mijmeren. We hebben geen eigen locatie en ook geen vaste momenten waarin we bezig zijn voor JobHulpMaatje.
					Voor het verspreiden van de informatie over en van JobHulpMaatje hebben we gelukkig het intranet. Dat probeert iedereen op de hoogte te houden met berichten en de agenda. Is het belangrijk? Dan staat het erop.</p>
					
					<img src="img/whatsapp/nopictures.png" class="my-2 float-left" style="width: 40%; margin-right: 15px;" alt="nopictures">
					<h5>De WhatsApp groepsapp</h5>
					<p>Maar dat gaat slechts één kant op. Gelukkig is er ook nog de groepsapp van WhatsApp. Hierin is iedereen opgenomen die actief is bij JobHulpMaatje Zoetermeer. De Whatsapp groepsapp is als een schoolplein. Wat je daar zegt kan iedereen lezen en zien. En iedereen kan reageren. En het is vluchtig. Wat je er vandaag op zet, is morgen misschien wel weer achter de horizon verdwenen.</p>
					
					<p>De Whatsapp groep is dus belangrijk voor ons. Maak er gebruik van als je iets kwijt wilt aan je mede-vrijwilligers. Liefst iets wat met JobHulpMaatje te maken heeft maar ook felicitaties bij verjaardagen of andere dingen die je graag aan je collega’s kwijt wil mogen hier worden geplaatst. Zo hebben we contact met elkaar, ook al is maar het digitaal. En dat is belangrijk.</p>
					<img src="img/whatsapp/getaroom.png" class="my-2 float-right" style="width: 40%; margin-left: 15px;" alt="getaroom">
					<p>Er zijn wel een paar regels die eigenlijk vanzelfsprekend zijn:</p>
					<ol>
					<li>Blijf fatsoenlijk</li>
					<li>Blijf beleefd</li>
					<li>Blijf terzake</li>
					</ol>
					<p>Als het nodig is kan er ingegrepen worden. Maar hé! We zijn toch allemaal nette mensen bij JobHulpMaatje Zoetermeer? Dus het zal wel meevallen <nobr>;-)</nobr></p>
					<img src="img/whatsapp/okbye.png" class="my-2 float-left" style="width: 40%; margin-right: 15px;" alt="okbye.png">
					<p>Als je niet houdt van meekletsen op een schoolplein dan kun je besluiten alleen mee te luisteren. Als je daar ook niet van houdt dan kun je het schoolplein natuurlijk ook verlaten. Toegang is niet verplicht. Doe alleen mee als het het leuk of nuttig vindt. Of beide natuurlijk! Want juist onder deze uitzonderlijke omstandigheden moeten we elkaar zoveel mogelijk vasthouden, ook in 2022 en verder.</p>
					';


$newsmsg[5] = '<h3 class="bluefont" id="dubbelslag">Dubbelslag in het Streekblad</h3>
					<h5 class="bluefont">17-12-2021</h5>
					<p>Deze week werd JobHulpMaatje Zoetermeer tweemaal in het Streekblad vermeld. Het komende afscheid van Johan en de afloop van de JobGroup waren de moeite waard om onder de aandacht te brengen.</p>
					<figure class="figure">
  						<img src="img/IMG_1607.jpeg" class="figure-img img-fluid" alt="Streekblad 1">
					</figure>
					<figure class="figure">
					  <img src="img/IMG_1608.jpeg" class="figure-img img-fluid" alt="Streekblad 2">
					</figure>
					';

$newsmsg[4] = '<h3 class="bluefont" id="jobgroup2021-3">Laatste JobGroup van 2021 afgesloten</h3>
					<h5 class="bluefont">12-12-2021</h5>
					<figure class="figure">
					  <img src="img/IMG_1570.jpeg" class="figure-img img-fluid" alt="JobGroup 2021-3">
					  <figcaption class="figure-caption">Staand van links naar rechts: Paul, Mona, Vivian. Zittend: Jan, Paula.</figcaption>
					</figure>
					<p>Afgelopen vrijdag 10 december sloten we de laatste JobGorup van dit jaar af. Door de coronamaatregelen moesten we uitwijken naar Café Max in de bibliotheek. 
					Een café dat overigens nog niet in gebruik is en daarom door ons gebruikt mocht worden. Niet ideaal maar dat ons aanpassingsvernmogen is groot is bleek uit de prima presentaties die de afsluitende deelnemers lieten horen. 
					Na het commentaar, de tips en de tricks van de toehoorders  en het uitreiken van de certificaten,
					was het tijd voor napraten en een lekkere tractatie.</p>
					<p>Afgesproken is dat de jobgroupleiders en de deelnemers over ruim een maand weer samenkomen om te kijken hoe het ieder vergaat. En intussen willen ze allemaal graag een maatje voor een persoonlijke begeleiding. Ook
					dat gaan we regelen natuurlijk.</p>
					
					';



$newsmsg[3] = '<h3 class="bluefont">Weer in het Streekblad</h3>
					<h5 class="bluefont">11-11-2021</h5>
					<p>Met een mooi stuk over de afsluiting van de JobGroup ZZP die op 5 november jl. plaats vond, is Corrie Buren er weer in geslaagd JobHulpMaatje Zoetermeer onder de aandacht te brengen in het Streekblad.</p>
					<img src="img/IMG_1444.jpeg" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Streekblad">
					';



$newsmsg[2] = '<h3 class="bluefont">Nieuwe posters en flyers</h3>
					<h5 class="bluefont">8-11-2021</h5>
					<img src="img/IMG_1442.jpeg" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Posters">
					<p>De mensen waarop JobHulpMaatje zich richt zijn niet altijd makkelijk te bereiken. En juist nu, in deze Corona-tijd, zijn velen voorzichtig met het zoeken van hulp. Ook onze hulp.</p>
					<p>Daarom willen we de toegang tot onze diensten zo laagdrempelig mogelijk aanbieden. Heel belangrijk daarbij is dat JobHulpMaatje als naam bekend wordt bij allerlei andere organisaties die hulp bieden op vele terreinen.
					Organisaties als Piëzo, Inzet, het Leerwerkloket, SchuldHulpMaatje etc. zijn, net als wij, in de weer om mensen die het nodig hebben en dat ook willen, aan een betere en sterkere maatschappelijke positie te helpen.</p>
					<p>Met nieuwe posters die we op zoveel mogelijk plaatsen willen op hangen en flyers die we kunnen uitdelen, hopen we bekender te worden. Zodat mensen ons makkelijk en snel kunnen vinden en wij ze verder helpen bij het vinden van 
					passend werk.</p>
					
					<p>Weet jij ook nog plekken waar deze posters zouden kunnen hangen? Laat het even weten met een email naar <a href="mailto: corrieburen@kpnmail.nl">Corrie Buren</a> of <a href="mailto: jang@jhm-zoetermeer.nl">Jan Geerdes</a>.
					Zij zorgen ervoor dat je snel het materiaal binnen krijgt en het kan gebruiken. Zoetermeer verdient het.
					Alvast bedankt!</p>
					';



$newsmsg[1] = '<h3 class="bluefont">Uitnodiging studiemiddag geldzaken</h3>
					<h5 class="bluefont">4-11-2021</h5>
					<h2>15-11-2021 AFGELAST! vanwege Corona</h2>
					<p>De gemeente Zoetermeer neemt op veel gebieden initiatief om armoede binnen de gemeentegrenzen te bestrijden. Een belangrijk aandachtspunt is er voor geldzaken, alles dat te maken heeft met inkomen en uitgaven van inwoners.</p>
					<p>Hoewel de activiteiten van JobHulpMaatje Zoetermeer slechts zijdelings te maken hebben met dit onderwerp, is deze studiemiddag zeker ook interessant voor maatjes. Bij deze word je dan ook van harte uitgenodigd om deel te nemen aan de studiemiddag
					die rond het onderwerp Geldzaken is georganiseerd.</p>
					<p>Tip: deze bijeenkomst is uiteraard ook nuttig als mogelijke uitbreiding van je eigen netwerk als maatje.</p>
					<div style="border: solid 1px blue; padding: 7px; font-style: italic;">
					<table>
						<tr><td>Datum :&nbsp;&nbsp;</td><td>Woensdag 17 november 2021</td></tr>
						<tr><td>Tijdstip :</td><td>Ontvangst vanaf 13:00h</td></tr>
						<tr><td></td><td>Aanvang studiemiddag 13:30h</td></tr>
						<tr><td></td><td>Afsluitende borrel 17:15h</td></tr>
						<tr><td></td><td>Einde studiemiddag 18:00h</td></tr>
						<tr><td>Locatie :</td><td>NH Hotel - Danny Kayelaan 20, 2719 Zoetermeer</td></tr>
						<tr><td>Kosten :</td><td>Deze studiemiddag wordt u kostenloos aangeboden</td></tr>
					</table><br/>
					<p>Wat gaan we doen?</p>
					<p>De dag start met een plenaire bijeenkomst van Roeland van Geuns met het thema: “Waarom is schuldhulpverlening zo ingewikkeld”</p>
					<p>Verder zijn er twee workshoprondes. U kunt aangeven welke workshops u zou willen volgen. Wij proberen zoveel mogelijk rekening te houden met ieders keuze.</p>
					<p>Voorwaarde deelname:</p>
					
					<p>Gezien de huidige corona maatregelen, moeten we je ook vragen om een QR code of negatieve PCR test te overhandigen bij binnenkomst. Zonder dit, kunnen wij u helaas niet toelaten.</p>
					<p>Meld u aan via de onderstaande link:</p>
					
					<p><a href="https://docs.google.com/forms/d/e/1FAIpQLSdOHJxQC4SI0ppqP9sas20r7ygs35Av6P8Z-rqLTfBCNKpkig/viewform?usp=sf_link" target="_new">docs.google.com/forms</a></p>
					<p>Na aanmelding ontvangt u een bevestiging.</p>
					</div>
					';
					

$newsmsg[0] = '<h3 class="bluefont">Nieuwe coronamaatregelen</h3>
					<h5 class="bluefont">3-11-2021</h5>
					<p>Afgelopen dinsdag zijn door de overheid strengere maatregelen genomen tegen de verdere verspreiding van het Corona-virus. De maatregelen gaan in op zaterdag 6 november en
					zullen ook gevolgen hebben voor JobHulpMaatje.</p>
					<p>Zo wordt op veel plaatsen het dragen van mondkapjes weer verplicht, met name in openbare, afgesloten ruimten zoals de bibliotheek/forum en
					andere plekken die we gebruiken zoals ShareBizz en de Kapelaan.</p>
					<p>Verder wordt ook op steeds meer plaatsen vereist dat je voor toegang een geldige QR-code moet kunnen laten zien waaruit blijkt dat je volledig bent gevaccineerd of bent genezen van Covid-19. Je krijgt ook een QR-code als je 
					je 24 uur of korter voor Corona hebt laten testen en een negatieve uitslag daarvan hebt.</p>
					<p>Ons advies? Laat je vaccineren alsjeblieft. Het helpt niet alleen jezelf maar ook alle mensen die dicht bij je in de buurt komen.</p>
					<img src="img/niet-coronatoegangsbewijs-1920.png" class="my-2 float-right float-right" style="width: 100%; margin-left: 15px;" alt="Teams">
					<p>Voor toegang tot de bibliotheek is geen Corona-toegangsbewijs nodig maar voor ShareBizz en de Kapelaan wel. Of wij voor bijeenkomsten in de bibliotheek als een JobGroup ook de QR-code zullen vragen, is
					afhankelijk van de JobGroup-leiding. Deelnemers zullen tijdig op de hoogte worden gebracht.</p>
					';

	return $newsmsg;

}
