<?php

function getMsgs ($number, $naam)
{
$newsmsg = array();

$newsmsg[19] = '<h3 class="bluefont">Nieuwe maatjesavond 10 september</h3>
				<h5 class="bluefont">28-8-2025</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/stadhuisforum.jpg" class="figure-img img-fluid" alt="stadhuisforum">
				</figure>
				<p>Al snel houden we de eerste maatjesavond van deze herfst. We hebben een boel te bespreken. Zoals jullie allemaal gezien hebben is het nieuwe programma voor dit najaar uitgekomen. Op Facebook draait de eerste reclamecampagne van dit seizoen.</p>
				<p>Woensdagavpnd 10 september komen we bij elkaar om te bespreken wat we gaan doen. Jullie inbreng is daarbij belangrijk. Dus wees er bij! We hebben je hulp nodig.</p>
				<p>Onderwerpen zijn o.a.:</p>
				<ul>
				<li>Introductie programma workshops 2e helft 2025, door Flip</li>
				<li>Reflectie op ons werk. <a href="docs/Notulen JHM_trainers_def-250825.pdf">De notulen van Jos</a> kunnen daarvoor dienen. Misschien hebben aanwezigen nog andere punten, door Jos</li>
				<li>Succesfactoren. Recent boekten we drie geslaagde trajecten naar werk. Wat waren de succesfactoren? Zijn er nog meer? door allen</li>
				<li>Informatie van bestuur en coördinatoren</li>
				</ul>
				<p>En natuurlijk vinden we het fijn om iedereen weer eens te zien en te spreken. We hopen dat je erbij bent. Schrijf je in!				
				<p>Tot 10 september.<br/>Joke en Marius</p>				
				<p><a class="btn btn-primary" href="pages/presence_list.php" role="button">Maatjesavond aan/afmelden &raquo;</a></p>
				
				';



$newsmsg[18] = '<h3 class="bluefont">De zomer is weer voorbij</h3>
				<h5 class="bluefont">25-8-2025</h5>
				<p>Nu de vakanties er weer op zitten, nou ja, in ieder geval de schoolvakanties, starten we weer met onze activiteiten. Veel voorbereidingen zijn  er al getroffen. Zo zijn er voor deze herfst maar liefst 15 nieuwe workshops gepland. En natuurlijk houden we iedere donderdagmiddag weer een spreekuur voor mensen die vragen hebben of zich willen inschrijven voor een workshop. Als je hier meer over wilt weten, kun je <a href="/agenda.php">de agenda</a> bekijken.</p>
				<p><a href="https://jobhulpmaatjezoetermeer.nl" target="_new">De publieke website</a> is ook weer helemaal bijgewerkt. Ook hier is de agenda in te zien. Hier kun je ook de flyer downloaden. Die staat <a href="https://jobhulpmaatjezoetermeer.nl/stichting.php#downloads" target="_new">hier</a>.</p>
				<p>Natuurlijk willen we onze activiteiten zoveel mogelijk bekend maken bij de mensen die we willen helpen. Daarvoor zijn er flyers gedrukt die we willen verspreiden op de juiste locaties. Ook zullen er weer diverse reclamecampagnes op Facebook worden gevoerd. Die bleken behoorlijk succcesvol in het verleden. En uiteraard willen we ons regelmatig laten zien in het Zoetermeerse Streekblad met artikeltjes die onze correspondent Corrie Buren aanlevert.</p>
				<figure class="figure float-left" style="width: 100%; margin-right: 0px;">
				<img src="img/2025najaarsprogramma.png" class="figure-img img-fluid" alt="2025 Najaarsprogramma">
				</figure>
				';

$newsmsg[17] = '<h3 class="bluefont">Zomerstop en terugblik JobHulpMaatje Zoetermeer</h3>
				<h5 class="bluefont">16-7-2025</h5>
				<figure class="figure float-left" style="width: 50%; margin-right: 15px;">
				<img src="fotoos_person/jokesikking2.jpg" class="figure-img img-fluid" alt="Joke Sikking">
				</figure>
				<p>Zomerstop inloopmiddagen op donderdag.</p>
				<p>De laatste inloopmiddag is 31 juli en na de zomerstop starten de inloopmiddagen weer op donderdag 4 september.
				Natuurlijk kunt u ons in deze periode wel benaderen via de website of telefonisch.</p>
				
				<p>Dat werkzoekenden JobHulpMaatje weten te vinden blijkt wel uit de goed bezochte inloopmiddagen. Wekelijks vonden hier veel nieuwe intakegesprekken plaats en konden werkzoekenden vaak direct na hun intake deelnemen aan de workshops op vrijdagochtend.
				Waar nodig werden Maatjes aan werkzoekenden gekoppeld, zodat werkzoekenden één op één begeleiding kregen.</p>
				
				<p>De 22 workshops in de eerste helft van 2025 werden bijgewoond door 41 unieke deelnemers. 12 Deelnemers hebben het JobGroup certificaat ontvangen omdat zij aan tenminste 7 workshops met verschillende thema’s hebben deelgenomen.</p>
				
				<p>Vanaf 12 september gaat er weer een nieuwe serie workshop van start.</p>
				
				<p>Namens JobHulpmaatje Zoetermeer<br>
				Joke Sikking</p>
				
				<p><a href="https://jobhulpmaatjezoetermeer.nl">Website www.jobhulpmaatjezoetermeer.nl</a></p>
				
				';

$newsmsg[16] = '<h3 class="bluefont">Vakantiegroet van de voorzitter</h3>
				<h5 class="bluefont">15-7-2025</h5>
				<figure class="figure float-left" style="width: 50%; margin-right: 15px;">
				<img src="fotoos_person/janwaaijer2.jpg" class="figure-img img-fluid" alt="Jan Waaijer">
				</figure>
				<p>“Ons goede werk kent diverse invalshoeken. Zelf probeer ik JobHulpMaatje bij anderen in onze samenleving onder te aandacht te brengen en soms leidt dat tot mooie dingen en soms tot teleurstellingen. De arbeidsmarkt is (politiek) niet sexy.</p>
				<p>Een andere kant is de persoonlijke en individuele invalshoek. Het doet mij altijd goed als ik mensen met enthousiasme en inzet onze bijeenkomsten en contactmomenten waarneem. In stilte geniet ik dan.</p>
				<p>Jullie verdienen een mooie zomer, die ik jullie van harte toewens, en na de vakantie met energie aan de slag voor de goede zaak.</p>
				<p>Tot ziens"</p>				
				<p>Jan Waaijer</p>
				';

$newsmsg[15] = '<h3 class="bluefont">Verslag maatjesavond 11 juni</h3>
				<h5 class="bluefont">19-6-2025</h5>
				<figure class="figure float-right" style="width: 50%; margin-left: 15px;">
				<img src="img/ztmwcregio.png" class="figure-img img-fluid" alt="Werkcentrum regio">
				</figure>
				<p>Vorige week woensdag waren een aantal maatjes van JobHulpMaatje Zoetermeer op bezoek in het nieuwe Werkcentrum Zoetermeer. Lees hier het verslag.</p>
				<p><a class="btn btn-primary" href="docs/maatjesavondinwerkcentrum.pdf" role="button">Lees het verslag &raquo;</a></p>
				';

$newsmsg[14] = '<h3 class="bluefont">Jobhulp Culemborg op bezoek</h3>
				<h5 class="bluefont">11-6-2025</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 0px;">
				<img src="img/stichtingjobhulpculemborg1.jpg" class="figure-img img-fluid" alt="JobHulp Culemborg">
				</figure>
				<p>Op 5 juni bezocht een delegatie van drie personen van Jobhulp Culemborg Zoetermeer voor een gesprek met JobHulpMaatje Zoetermeer. Jan Waaijer, Flip Bakker en ondergetekende voerden het gesprek.</p>
				<p>Jobhulp Culemborg is de oudste JobHulpMaatje en opgericht in 2015. Zoetermeer startte in 2018 een locatie. Culemborg heeft aan de basis gestaan van de ontwikkeling van de opzet van het cursusmateriaal. In het gesprek viel direct op dat de aanpak van beide locaties nog steeds vrij goed op elkaar lijkt. Culemborg is ook succesvol met meer dan zestig deelnemers in 2024 waarvan de helft werk vond.</p> 
				<p>Omdat de gemeente Culemborg minder subsidie gaat geven wilden zij vooral van Zoetermeer weten hoe wij het goedkopere Zoetermeerse model met meerdere coördinatoren en zonder betaalde krachten vorm hebben gegeven. Mogelijk dat Culemborg ook die kant op gaat, want zij willen graag doorgaan. En zij wilden ook graag weten hoe met alleen vrijwilligers de samenhang bewaard kan blijven, hoe de informatievoorziening georganiseerd is en hoe de administratie en registratie is geregeld.</p> 
				<p>Daarnaast waren de Culemborgers ook geïnteresseerd in de aanpak van de Workshops als JobGroups nieuwe stijl. Flip gaf een presentatie en gaf de uitwerking aan hen mee. Het werken met het pakket TRJCT  van LDC wekte ook hun belangstelling.</p>
				<p>Peter adviseerde hen nog aansluiting te zoeken bij de andere locaties via Nederland Geldzorgenvrij. De kosten zijn laag en het helpt je in praktische zin bij bijvoorbeeld trainingen en handboeken en je hoort zo waar locaties tegenaan lopen en hoe daar mee omgegaan wordt.</p>
				<p>Peter Veld, juni 2025</p>

				';

$newsmsg[13] = '<h3 class="bluefont">Werkcentrum maakt er werk van</h3>
				<h5 class="bluefont">28-5-2025</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 0px;">
				<img src="img/gvs05622a.jpg__3000x2004_q85_subsampling-2.jpg" class="figure-img img-fluid" alt="JobHulpMaatje">
				</figure>
				<p>Op 11 juni is de volgende maatjesavond. Deze vindt plaats in het nieuwe Werkcentrum Zuid-Holland. Het werkcentrum laat er geen gras 
				over groeien en heeft JobHulpMaatje uitgebreid geïntroduceerd op haar splinternieuwe website.</p>
				<p>Het belooft 11 juni een interessante avond te worden en we hopen op een behoorlijke opkomst.</p>
				<p>Benieuwd wat het Werkcentrum van ons zegt? Klik op de knop hieronder. En meld je alsnog aan via de knop in het eerdere bericht.</p>
				<p><a class="btn btn-primary" href="https://werkcentrumzuidhollandcentraal.nl/nieuws/jobhulpmaatje-geeft-persoonlijke-hulp-bij-het-vinden-van-werk/" role="button target="_new">Werkcentrum over ons &raquo;</a></p>
				';

$newsmsg[12] = '<h3 class="bluefont">Een speciale maatjesavond</h3>
				<h5 class="bluefont">21-5-2025</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 0px;">
				<img src="img/WerkcentrumZH.png" class="figure-img img-fluid" alt="werkcentrumZH">
				</figure>
				<p>Samenwerken is de sleutel tot succes voor JobHulpMaatje in de toekomst.</p>
				<p>De volgende maatjesavond, op woensdag 11 juni, bespreken we de mogelijkheden met het Werkcentrum Zoetermeer.</p>
				<p>Lees er meer over achter de knop.</p>
				<p><a class="btn btn-primary" href="pages/bericht20250521_1.php" role="button target="_new">Over de maatjesavond &raquo;</a></p>
				<p><a class="btn btn-primary" href="pages/presence_list.php" role="button">Maatjesavond aan/afmelden &raquo;</a></p>
				';

$newsmsg[11] = '<h3 class="bluefont" id="jaarverslag">Hoe was 2024 voor JobHulpMaatje Zoetermeer?</h3>
				<h5 class="bluefont">14-3-2025</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/jaarverslag2024.jpg" class="figure-img img-fluid" alt="jaarverslag 2024">
				<figcaption class="figure-caption">Jaarverslag voorpagina</figcaption>
				</figure>
				<p>Het afgelopen jaar was voor JobHulpMaatje weer een succesvol jaar. Samen met alle maatjes zijn ook in 2024 weer vele mensen geholpen in hun zoektocht naar passend werk.</p>
				<p>De meer dan 35 workshops en de vele Walk&Talk\'s zijn goed bezocht. Tot slot werd ook de afsluitende avond met de partners van JobHulpMaatje in stijl gehouden in een voor iedereen plezierige ambiance.</p>
				<p>Dit alles is terug te lezen in het jaarverslag over 2024. Als je ook nog wilt weten hoe de euro\'s rolden, lees dan het financieel jaarverslag.</p>
				<p><a class="btn btn-primary" href="https://jobhulpmaatjezoetermeer.nl/nieuws.php" role="button target="_new">Naar het jaarverslag 2024 &raquo;</a></p>
				';



$newsmsg[10] = '<h3 class="bluefont">Verslag maatjesavond</h3>
				<h5 class="bluefont">13-3-2025</h5>
				<p>De eerste maatjesavond zit er weer op. En er was veel informatie. Peter heeft een kort verslag geschreven dat je kunt lezen via onderstaande knop.</p>
				
				<p><a class="btn btn-primary" href="pages/bericht20250313_1.php" role="button">Verslag lezen &raquo;</a></p>
				<figure class="figure float-right" style="width: 100%; margin-left: 0px;">
				<img src="img/maatjesavond2503121.jpg" class="figure-img img-fluid" alt="Maatjesavond">
				</figure>

				';
				

$newsmsg[9] = '<h3 class="bluefont">Eerste maatjesavond van 2025</h3>
				<h5 class="bluefont">20-2-2025</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/stadhuisforum.jpg" class="figure-img img-fluid" alt="stadhuisforum">
				</figure>
				<p>Hierbij nodigen wij je uit voor de eerste maatjesavond van dit jaar in het Forum.</p>
				
				<p> We zijn nog niet helemaal zeker van de agenda. Deze volgt zodra we \'m definitief hebben vastgesteld. In ieder geval zal het gebruik van de testen bij het LDC een grote rol spelen.</p>
				<p>Veel maatjes hebben al via Whatsapp laten weten of ze komen of niet. Toch willen we je vragen dat ook nog te laten weten in de presentielijst die je ziet als je onderstaande knop gebruikt. Een antwoord daar kun je elk moment weer wijzigen als je dat nodig vindt.</p>
				<p>Uiteraard hopen we op je aanwezigheid. Niet alleen omdat het nuttig is maar misschien nog wel meer omdat we je graag zien en spreken!</p>
				<p>Tot dan.<br/>Joke en Marius</p>
				
				<p><a class="btn btn-primary" href="#" role="button">Maatjesavond aan/afmelden &raquo;</a></p>
				
				';
				
				
$newsmsg[8] = '<h3 class="bluefont">Nieuwe brochure</h3>
				<h5 class="bluefont">17-1-2025</h5>
				<p>Ook dit jaar verzorgt JobHulpMaatje weer een flink aantal workshops voor mensen die graag wat hulp ontvangen bij het zoeken naar werk.</p>
				<p>De meeste workshops worden als vanouds vakkundig verzorgd door Flip Bakker. Enkele workshops, ieder met een specifiek thema, worden door diverse gastsprekers verzorgd.</p>
				<p>We hopen uiteraard op een flinke belangstelling en zullen regelmatig via de Social Media bekend maken wanneer de workshops worden gehouden.</p>
				<p>Wil je de bijbehorende brochure zien? Klik dan op de button.</p>
				<p><a class="btn btn-primary" href="pages/bericht20250117_1.php" role="button">Bekijk de flyer &raquo;</a></p>
				<figure class="figure float-left" style="width: 100%; margin-right: 0px;">
				<img src="img/2025voorjaarsprogramma1.jpg" class="figure-img img-fluid" alt="flyer">
				</figure>

';
$newsmsg[7] = '<h3 class="bluefont">Nieuwe berichten</h3>
				<h5 class="bluefont">5-12-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/firefoxnbs.png" class="figure-img img-fluid" alt="nieuwsberichten">
				</figure>
				<p>Op de publieke website staan nu twee nieuwe berichten. Misschien niet voor iedereen nieuws maar toch belangrik genoeg om de nieuwsfeiten op de website onder de aandacht te brengen.</p>
				<p>Klik op bijgaand knop om ze te lezen.</p>
				<p><a class="btn btn-primary" href="https://jobhulpmaatjezoetermeer.nl/nieuws.php" role="button">Lees het nieuws &raquo;</a></p>
';


$newsmsg[6] = '<h3 class="bluefont">Kerst Maatjesavond</h3>
				<h5 class="bluefont">1-12-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/kerstborrel.jpg" class="figure-img img-fluid" alt="kerstborrel">
				</figure>
				<p>Het jaar loopt weer ten einde, tijd om weer de rekening op te maken van onze activiteiten in het afgelopen jaar. Op maandagavond 16 december as. vanaf 19:30h ben je welkom in de Kapelaan.</p>
				<p>Deze avond besteden we aan een terug- en aan een vooruitblik van JobHulpMaatje in onze gemeente. Wat ging goed (veel!) en wat kan nog beter (altijd wel iets toch?).</p>
				<p>Bovendien hopen we nog veel meer mensen te mogen begroeten deze avond. Wie? Dat volgt later. Het belooft een feestelijke avond te worden.</p>
				<p>Wees erbij om het mee te maken en schrijf je in! Noteer 16 december in je agenda.</p>
				
				<!-- <p><a class="btn btn-primary" href="pages/presence_list.php" role="button">Ik kom naar de Maatjesavond &raquo;</a></p> -->
				
';


$newsmsg[5] = '<h3 class="bluefont">Persbericht JobHulpMaatje in het Streekblad</h3>
				<h5 class="bluefont">28-11-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/persbericht241128.jpg" class="figure-img img-fluid" alt="persbericht">
				</figure>
				
				';


$newsmsg[4] = '<h3 class="bluefont">Presentatie Peter Veld van 4-11-2024</h3>
				<h5 class="bluefont">6-11-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/presentatie-PV.jpg" class="figure-img img-fluid" alt="presentatie">
 				</figure>
				<p>Op de laatste maatjesavond van 4 -11-2024 gaf Peter Veld een presentatie over de werkgelegenheidsproblematiek in Zoetermeer en omgeving. Op veler verzoek kun je hier de integrale 
				presentatie vinden in PDF-formaat. Deze is te downloaden. Als je op onderstaande link drukt, kun je de presentatie als download zo binnenhalen.</p>
				
				<p><a href="docs/presentatie04112024.pdf" download="presentatie04112024.pdf">Presentatie 4-11-2024&nbsp&nbsp&nbsp;<i class="fas fa-download"></i></a></p>
				';


$newsmsg[3] = '<h3 class="bluefont">Derde maatjesavond van 2024</h3>
				<h5 class="bluefont">13-9-2024</h5>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/stadhuisforum.jpg" class="figure-img img-fluid" alt="stadhuisforum">
 				</figure>
				<p>Hierbij nodigen wij je uit voor de derde maatjesavond van dit jaar in het Forum.
				
				We sluiten om 21:30 uur af. Wie wil, kan blijven voor onderling contact. We zorgen voor wat drinken en lekkers daarbij. Om 22:00 uur moeten we het pand écht verlaten.</p>
				<table>
					<tr><td>Datum</td><td>Woensdag 18 september 2024</td></tr>
					<tr><td>Plaats</td><td>Stadhuis Forum</td></tr>
					<tr><td></td><td>beneden in de Commissiezaal/trouwzaal</td></tr>	
					<tr><td>Tijdstip</td><td>Ontvangst vanaf 19:15h</td></tr>
					<tr><td>Aanvang</td><td>19:30h</td></tr>
					<tr><td>Einde</td><td>21:30h</td></tr>
					<tr><td></td><td>Nazit tot uiterlijk 22:00h</td></tr>
				</table><br/>
				<p>Programma</p>
				<table>
					<tr><td>19:30h&nbsp;&nbsp;</td><td>Opening en welkom door Joke</td></tr>
					<tr><td>19:40h&nbsp;&nbsp;</td><td>Mededelingen van bestuur en coördinatoren</td></tr>
					<tr><td>19:50h&nbsp;&nbsp;</td><td>Peter licht nieuwe ontwikkelingen en activiteiten toe</td></tr>	
					<tr><td>20:10h&nbsp;&nbsp;</td><td>Pauze</td></tr>
					<tr><td>20:30h&nbsp;&nbsp;</td><td>Werkwijze en gezamenlijke afspraken door Flip en Marius.</td></tr>
					<tr><td></td><td>De werkwijze van JobHulpMaatje in Zoetermeer is in de loop van de tijd wat losser geworden en misschien wel iets veranderd. Het gaat dan vooral om werkvolgorde en procedures. We willen hierover spreken, van gedachten wisselen en de neuzen weer meer in dezelfde richting krijgen. Maar ook andere zaken die het Maatje-zijn betreffen kunnen aan de orde komen.</td></tr>
					<tr><td>21:20h</td><td>Rondvraag</td></tr>
					<tr><td>21:30h&nbsp;&nbsp;</td><td>Sluiting</td></tr>
				</table><br/>
				  				
				<p>Je aanwezigheid is, zoals altijd, belangrijk! Samen maken we JobHulpMaatje en kunnen we meer betekenen voor onze medemens. We zien naar je uit.
				Laat even weten of je al dan niet van plan bent om te komen via Intranet, of anders aan Joke. Dat helpt ons in de voorbereidingen. Er is plaats voor 76 personen, dus leuk als je er bent 😊</p>
				<p>Als je nog niet hebt aangegeven of je komt of niet, doe dat ajb dan nu. Bij het invullen van de aanmeldingslijst lees je hoe je dat doet.</p>
				<p><a class="btn btn-primary disabled" href="#" role="button">Maatjesavond aan/afmelden &raquo;</a></p>
				
				';

$newsmsg[2] = '<h3 class="bluefont">Najaarsprogramma 2024</h3>
				<h5 class="bluefont">16-8-2024</h5>
				<p>De vakanties zijn bijna voorbij. Mensen gaan weer aan het werk. Of willen dat juist heel graag en zoeken een baan. Wij helpen daarbij, ook dit najaar.</p>
				<p>Het bestuur en de coördinatoren hebben ook voor het najaar van 2024 een programma opgesteld met workshops voor iedere werkzoekende. En voor de gelegenheid is weer een prachtige brochure 
				ontworpen.</p>
				<p>Het programma staat in de agenda van het intranet. Je kunt de flyer downloaden via de publieke website via onderstaande knop. Er is <a href="https://jobhulpmaatjezoetermeer.nl/nieuws">een nieuwsbericht op de website</a> waarnaar je kunt verwijzen als iemand meer informatie wil hebben.</p>
				<figure class="figure float-right" style="width: 100%; margin-left: 15px;">
				<img src="img/2024najaarsprogramma.jpg" class="figure-img img-fluid" alt="2024najaarsprogramma">
 				</figure>
				<p><a class="btn btn-primary" href="https://jobhulpmaatjezoetermeer.nl/stichting.php#downloads" role="button">Download hier de flyer &raquo;</a></p>
				';


$newsmsg[1] = '<h3 class="bluefont">Multiproblematiek</h3>
				<h5 class="bluefont">25-4-2024</h5>
				<p>Ook op de laatste maatjesavond kwam het onderwerp weer ter sprake: multiproblematiek. Duidelijk is dat dit begrip vaak een grote rol speelt bij de mensen die JobHulpMaatje op dit moment ondersteunt bij het zoeken naar geschikt werk. Want vaker wel dan niet spelen er meerdere zaken bij het vinden van passend werk. Zoals gezondheid, zowel lichamelijk als geestelijk, armoede, etniciteit, leeftijd, enz.</p>
				<p>Afgelopen zaterdag stond in het NRC een artikel waarin goed werd uitgelegd wat dit betekent voor mensen. En ook hoe lastig het kan zijn om deze mensen goed te helpen.</p>
				<figure class="figure float-left" style="width: 100%; margin-right: 15px;">
				<img src="img/saskiabrandewijn.png" class="figure-img img-fluid" alt="saskiabrandewijn">
				<figcaption class="figure-caption"><b>Saskia Brandewijn</b> kan door psychische problemen niet werken, maar krijgt geen arbeidsongeschiktheidsuitkering. „Wat maakt het uit of ik eerst gewerkt heb? Ik ben gewoon ziek.”</figcaption>
				 </figure>
				<p>Het artikel gaat voornamelijk over mensen die in de bijstand zitten en ziek zijn. Deze mensen ervaren op meerdere terreinen tegenslag en onbegrip. Mensen met wie ook wij soms te maken krijgen. Vandaar dat dit artikel lezenswaardig is voor ieder maatje.</p>
				<p><a class="btn btn-primary" href="docs/nrc-krant-20240420-4995671.pdf" role="button">Lees het artikel &raquo;</a></p>
				';

$newsmsg[0] = '<h3 class="bluefont">Verslag maatjesavond van 10 april</h3>
				<h5 class="bluefont">24-4-2024</h5>
				<p>De laatste maatjesavond vond twee weken geleden plaats. Niet iedereen was aanwezig. Hier kun je een kort verslag lezen dat Sjanet heeft gemaakt.</p>
				<p><a class="btn btn-primary" href="pages/bericht20240424_1.php" role="button">Lees het verslag &raquo;</a></p>
				';


	return $newsmsg;

}
